/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Standard success response model.  Attributes:     status (str): The status of the response. Defaults to \"success\".     message (str): A success message.
*/
export class CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    'status'?: string = 'success';
    'message': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CyborgdbServiceApiSchemasIndexSuccessResponseModel.attributeTypeMap;
    }
}

