/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Response model for listing all indexes.  Attributes:     indexes (List[str]): List of available index names.
*/
export class IndexListResponseModel {
    'indexes': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexes",
            "baseName": "indexes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return IndexListResponseModel.attributeTypeMap;
    }
}

