/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Response model for retrieving the training status of indexes.  Attributes:     training_indexes (List[str]): List of index names currently being trained.     retrain_threshold (int): The multiplier used for the retraining threshold.
*/
export class IndexTrainingStatusResponseModel {
    'trainingIndexes': Array<string>;
    'retrainThreshold': number;
    'workerPid': number;
    'globalTraining': { [key: string]: any; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trainingIndexes",
            "baseName": "training_indexes",
            "type": "Array<string>"
        },
        {
            "name": "retrainThreshold",
            "baseName": "retrain_threshold",
            "type": "number"
        },
        {
            "name": "workerPid",
            "baseName": "worker_pid",
            "type": "number"
        },
        {
            "name": "globalTraining",
            "baseName": "global_training",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return IndexTrainingStatusResponseModel.attributeTypeMap;
    }
}

