/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IndexIVFFlatModel } from './indexIVFFlatModel';
import { IndexIVFModel } from './indexIVFModel';
import { IndexIVFPQModel } from './indexIVFPQModel';

export class IndexConfig {
    'dimension'?: number;
    'type'?: string = 'ivfflat';
    'pqDim': number;
    'pqBits': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "pqDim",
            "baseName": "pq_dim",
            "type": "number"
        },
        {
            "name": "pqBits",
            "baseName": "pq_bits",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IndexConfig.attributeTypeMap;
    }
}

