/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Model for configuring an IVFFlat (Inverted File with Flat quantization) index.  Attributes:     type (str): Index type identifier. Defaults to \"ivfflat\".     n_lists (Optional[int]): Number of inverted lists (clusters). Defaults to 100.
*/
export class IndexIVFFlatModel {
    'dimension'?: number | null;
    'type'?: string = 'ivfflat';
    'nLists'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "nLists",
            "baseName": "n_lists",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IndexIVFFlatModel.attributeTypeMap;
    }
}

