/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Response model for retrieving information about an index.  Attributes:     index_name (str): The name of the index.     index_type (str): The type of index (e.g., IVF, IVFFlat, IVFPQ).     is_trained (bool): Indicates whether the index has been trained.     index_config (Dict[str, Any]): The full configuration details of the index.
*/
export class IndexInfoResponseModel {
    'indexName': string;
    'indexType': string;
    'isTrained': boolean;
    'indexConfig': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "indexType",
            "baseName": "index_type",
            "type": "string"
        },
        {
            "name": "isTrained",
            "baseName": "is_trained",
            "type": "boolean"
        },
        {
            "name": "indexConfig",
            "baseName": "index_config",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return IndexInfoResponseModel.attributeTypeMap;
    }
}

