/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Model for configuring an IVFPQ (Inverted File with Product Quantization) index.  Attributes:     type (str): Index type identifier. Defaults to \"ivfpq\".     pq_dim (int): Dimensionality of PQ codes.     pq_bits (int): Number of bits per quantizer.
*/
export class IndexIVFPQModel {
    'dimension'?: number | null;
    'nLists': number;
    'metric'?: string | null;
    'type'?: string = 'ivfpq';
    'pqDim': number;
    'pqBits': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "number"
        },
        {
            "name": "nLists",
            "baseName": "n_lists",
            "type": "number"
        },
        {
            "name": "metric",
            "baseName": "metric",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "pqDim",
            "baseName": "pq_dim",
            "type": "number"
        },
        {
            "name": "pqBits",
            "baseName": "pq_bits",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IndexIVFPQModel.attributeTypeMap;
    }
}

