/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IndexOperationRequest } from './indexOperationRequest';

/**
 * Request model for listing all IDs in the index.
 */
export class ListIDsRequest extends IndexOperationRequest {
    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        ...IndexOperationRequest.attributeTypeMap
    ];

    static getAttributeTypeMap() {
        return ListIDsRequest.attributeTypeMap;
    }
}