/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Results } from './results';

/**
* Response model for similarity search queries.  Attributes:     results (List[QueryResultItem]): List of search results.
*/
export class QueryResponse {
    'results': Results;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Results"
        }    ];

    static getAttributeTypeMap() {
        return QueryResponse.attributeTypeMap;
    }
}

