/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QueryResultItem } from './queryResultItem';

/**
 * Response model for similarity search queries.
 * Attributes:
 *   results: Can be either a list of QueryResultItem (for single queries)
 *   or a list of lists of QueryResultItem (for batch queries)
 */
export class QueryResponse {
    // This property can hold either a flat list of results (for single queries)
    // or a nested list of results (for batch queries)
    'results': QueryResultItem[] | QueryResultItem[][];

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<QueryResultItem> | Array<Array<QueryResultItem>>"
        }
    ];

    static getAttributeTypeMap() {
        return QueryResponse.attributeTypeMap;
    }
    
    /**
     * Helper method to determine if this is a batch response
     */
    isBatchResponse(): boolean {
        return Array.isArray(this.results) && 
               this.results.length > 0 && 
               Array.isArray(this.results[0]);
    }

    /**
     * Get the first result set (useful for single queries or first batch result)
     */
    getFirstResultSet(): QueryResultItem[] {
        if (this.isBatchResponse()) {
            return (this.results as QueryResultItem[][])[0];
        } else {
            return this.results as QueryResultItem[];
        }
    }
}