/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Request model for performing a similarity search in the encrypted index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     query_vector (Optional[List[float]]): The vector used for the similarity search.     query_contents (Optional[str]): Text-based content used for semantic search.     top_k (int): Number of nearest neighbors to return for each query. Defaults to 100.     n_probes (int): Number of lists to probe during the query. Defaults to 1.     greedy (bool): Whether to use greedy search. Defaults to False.     filters (Optional[Dict[str, Any]]): JSON-like dictionary specifying metadata filters. Defaults to {}.     include (List[str]): List of additional fields to include in the response. Defaults to `[\"distances\"]`.
*/
export class QueryRequest {
    /**
    * 32-byte encryption key as hex string
    */
    'indexKey': string;
    /**
    * ID name
    */
    'indexName': string;
    'queryVector'?: number[] | null;
    'queryContents'?: string | null;
    'topK'?: number = 100;
    'nProbes'?: number = 1;
    'greedy'?: boolean = false;
    'filters'?: object | null;
    'include'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexKey",
            "baseName": "index_key",
            "type": "string"
        },
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "queryVector",
            "baseName": "query_vector",
            "type": "Array<number>"
        },
        {
            "name": "queryContents",
            "baseName": "query_contents",
            "type": "string"
        },
        {
            "name": "topK",
            "baseName": "top_k",
            "type": "number"
        },
        {
            "name": "nProbes",
            "baseName": "n_probes",
            "type": "number"
        },
        {
            "name": "greedy",
            "baseName": "greedy",
            "type": "boolean"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "object"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return QueryRequest.attributeTypeMap;
    }
}

