/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BatchQueryRequest } from './batchQueryRequest';
import { QueryRequest } from './queryRequest';

export class Request {
    /**
    * 32-byte encryption key as hex string
    */
    'indexKey': string;
    /**
    * ID name
    */
    'indexName': string;
    'queryVectors': Array<Array<number>>;
    'queryContents'?: string;
    'topK'?: number;
    'nProbes'?: number;
    'greedy'?: boolean;
    'filters'?: { [key: string]: any; };
    'include'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexKey",
            "baseName": "index_key",
            "type": "string"
        },
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "queryVectors",
            "baseName": "query_vectors",
            "type": "Array<Array<number>>"
        },
        {
            "name": "queryContents",
            "baseName": "query_contents",
            "type": "string"
        },
        {
            "name": "topK",
            "baseName": "top_k",
            "type": "number"
        },
        {
            "name": "nProbes",
            "baseName": "n_probes",
            "type": "number"
        },
        {
            "name": "greedy",
            "baseName": "greedy",
            "type": "boolean"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Request.attributeTypeMap;
    }
}

