/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request model for training an index.  Attributes:     batch_size (int): Size of each batch for training. Default is 2048.     max_iters (int): Maximum iterations for training. Default is 100.     tolerance (float): Convergence tolerance for training. Default is 1e-6.     max_memory (int): Maximum memory (MB) usage during training. Default is 0 (no limit).
*/
export class TrainRequest {
    /**
    * 32-byte encryption key as hex string
    */
    'indexKey': string;
    /**
    * ID name
    */
    'indexName': string;
    'batchSize'?: number = 2048;
    'maxIters'?: number = 100;
    'tolerance'?: number = 1.0E-6;
    'maxMemory'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "indexKey",
            "baseName": "index_key",
            "type": "string"
        },
        {
            "name": "indexName",
            "baseName": "index_name",
            "type": "string"
        },
        {
            "name": "batchSize",
            "baseName": "batch_size",
            "type": "number"
        },
        {
            "name": "maxIters",
            "baseName": "max_iters",
            "type": "number"
        },
        {
            "name": "tolerance",
            "baseName": "tolerance",
            "type": "number"
        },
        {
            "name": "maxMemory",
            "baseName": "max_memory",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TrainRequest.attributeTypeMap;
    }
}

