/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import axios, { AxiosRequestConfig, AxiosResponse } from 'axios';

/* tslint:disable:no-unused-locals */
import { CreateIndexRequest } from '../model/createIndexRequest';
import { CyborgdbServiceApiSchemasIndexSuccessResponseModel } from '../model/cyborgdbServiceApiSchemasIndexSuccessResponseModel';
import { CyborgdbServiceApiSchemasVectorsSuccessResponseModel } from '../model/cyborgdbServiceApiSchemasVectorsSuccessResponseModel';
import { DeleteRequest } from '../model/deleteRequest';
import { GetRequest } from '../model/getRequest';
import { GetResponseModel } from '../model/getResponseModel';
import { IndexInfoResponseModel } from '../model/indexInfoResponseModel';
import { IndexListResponseModel } from '../model/indexListResponseModel';
import { IndexOperationRequest } from '../model/indexOperationRequest';
import { ListIDsRequest } from '../model/listIDsRequest';
import { ListIDsResponse } from '../model/listIDsResponse';
import { QueryResponse } from '../model/queryResponse';
import { Request } from '../model/request';
import { TrainRequest } from '../model/trainRequest';
import { UpsertRequest } from '../model/upsertRequest';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { ApiKeyAuth } from '../model/models';

import { HttpError } from './apis';

let defaultBasePath = 'http://localhost';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum DefaultApiApiKeys {
    APIKeyHeader,
}

export class DefaultApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'APIKeyHeader': new ApiKeyAuth('header', 'X-API-Key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: DefaultApiApiKeys, value: string) {
        (this.authentications as any)[DefaultApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Create a new encrypted index with the provided configuration.
     * @summary Create Encrypted Index
     * @param createIndexRequest 
     */
    public async createIndexV1IndexesCreatePost (createIndexRequest: CreateIndexRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: CyborgdbServiceApiSchemasIndexSuccessResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/indexes/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'createIndexRequest' is not null or undefined
        if (createIndexRequest === null || createIndexRequest === undefined) {
            throw new Error('Required parameter createIndexRequest was null or undefined when calling createIndexV1IndexesCreatePost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(createIndexRequest, "CreateIndexRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "CyborgdbServiceApiSchemasIndexSuccessResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Delete a specific index.
     * @summary Delete Encrypted Index
     * @param indexOperationRequest 
     */
    public async deleteIndexV1IndexesDeletePost (indexOperationRequest: IndexOperationRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: CyborgdbServiceApiSchemasIndexSuccessResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/indexes/delete';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'indexOperationRequest' is not null or undefined
        if (indexOperationRequest === null || indexOperationRequest === undefined) {
            throw new Error('Required parameter indexOperationRequest was null or undefined when calling deleteIndexV1IndexesDeletePost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(indexOperationRequest, "IndexOperationRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "CyborgdbServiceApiSchemasIndexSuccessResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Delete vectors by their IDs.
     * @summary Delete Items from Encrypted Index
     * @param deleteRequest 
     */
    public async deleteVectorsV1VectorsDeletePost (deleteRequest: DeleteRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: CyborgdbServiceApiSchemasVectorsSuccessResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/vectors/delete';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'deleteRequest' is not null or undefined
        if (deleteRequest === null || deleteRequest === undefined) {
            throw new Error('Required parameter deleteRequest was null or undefined when calling deleteVectorsV1VectorsDeletePost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(deleteRequest, "DeleteRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "CyborgdbServiceApiSchemasVectorsSuccessResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * List all IDs currently stored in the index.
     * @summary List all IDs in an index
     * @param listIDsRequest 
     */
    public async listIDsV1VectorsListIdsPost (listIDsRequest: ListIDsRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: ListIDsResponse;  }> {
        const localVarPath = this.basePath + '/v1/vectors/list_ids';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'listIDsRequest' is not null or undefined
        if (listIDsRequest === null || listIDsRequest === undefined) {
            throw new Error('Required parameter listIDsRequest was null or undefined when calling listIDsV1VectorsListIdsPost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(listIDsRequest, "ListIDsRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "ListIDsResponse");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Get information about a specific index.
     * @summary Describe Encrypted Index
     * @param indexOperationRequest 
     */
    public async getIndexInfoV1IndexesDescribePost (indexOperationRequest: IndexOperationRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: IndexInfoResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/indexes/describe';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'indexOperationRequest' is not null or undefined
        if (indexOperationRequest === null || indexOperationRequest === undefined) {
            throw new Error('Required parameter indexOperationRequest was null or undefined when calling getIndexInfoV1IndexesDescribePost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(indexOperationRequest, "IndexOperationRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "IndexInfoResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Retrieve vectors by their IDs.
     * @summary Get Items from Encrypted Index
     * @param getRequest 
     */
    public async getVectorsV1VectorsGetPost (getRequest: GetRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: GetResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/vectors/get';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'getRequest' is not null or undefined
        if (getRequest === null || getRequest === undefined) {
            throw new Error('Required parameter getRequest was null or undefined when calling getVectorsV1VectorsGetPost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(getRequest, "GetRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "GetResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Check if the API is running.
     * @summary Health check endpoint
     */
    public async healthCheckV1HealthGet (options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: { [key: string]: string; };  }> {
        const localVarPath = this.basePath + '/v1/health';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "{ [key: string]: string; }");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * List all available indexes.
     * @summary List Encrypted Indexes
     */
    public async listIndexesV1IndexesListGet (options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: IndexListResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/indexes/list';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "IndexListResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Search for nearest neighbors in the index.
     * @summary Query Encrypted Index
     * @param request Single query or batch query request
     */
    public async queryVectorsV1VectorsQueryPost(
        request: Request, 
        options: {headers: {[name: string]: string}} = {headers: {}}
    ): Promise<{ response: AxiosResponse; body: QueryResponse; }> {
        const localVarPath = this.basePath + '/v1/vectors/query';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'request' is not null or undefined
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling queryVectorsV1VectorsQueryPost.');
        }

        // Determine if this is a batch query (has query_vectors) or single query (has query_vector)
        const isBatchQuery = 'queryVectors' in request && Array.isArray(request.queryVectors);

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(request, "Request")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => 
                this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => 
            this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                
                // Parse the response body
                const queryResponse = ObjectSerializer.deserialize(response.data, "QueryResponse");
                
                // Ensure results are always in the correct format based on query type
                if (queryResponse.results) {
                    // If single item response but batch query was sent, wrap in an array
                    if (isBatchQuery && 
                        !Array.isArray(queryResponse.results[0]) && 
                        Array.isArray(queryResponse.results)) {
                        queryResponse.results = [queryResponse.results];
                    }
                    
                    // If batch response but single query was sent, unwrap it
                    if (!isBatchQuery && 
                        Array.isArray(queryResponse.results) && 
                        queryResponse.results.length === 1 && 
                        Array.isArray(queryResponse.results[0])) {
                        queryResponse.results = queryResponse.results[0];
                    }
                }
                
                return { response: response, body: queryResponse };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Train the index for efficient querying.
     * @summary Train Encrypted index
     * @param trainRequest 
     */
    public async trainIndexV1IndexesTrainPost (trainRequest: TrainRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: CyborgdbServiceApiSchemasIndexSuccessResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/indexes/train';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'trainRequest' is not null or undefined
        if (trainRequest === null || trainRequest === undefined) {
            throw new Error('Required parameter trainRequest was null or undefined when calling trainIndexV1IndexesTrainPost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(trainRequest, "TrainRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "CyborgdbServiceApiSchemasIndexSuccessResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

    /**
     * Add or update vectors in the index.
     * @summary Add Items to Encrypted Index
     * @param upsertRequest 
     */
    public async upsertVectorsV1VectorsUpsertPost (upsertRequest: UpsertRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: CyborgdbServiceApiSchemasVectorsSuccessResponseModel;  }> {
        const localVarPath = this.basePath + '/v1/vectors/upsert';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'upsertRequest' is not null or undefined
        if (upsertRequest === null || upsertRequest === undefined) {
            throw new Error('Required parameter upsertRequest was null or undefined when calling upsertVectorsV1VectorsUpsertPost.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(upsertRequest, "UpsertRequest")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.APIKeyHeader.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.APIKeyHeader.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(async () => {
            try {
                const response = await axios(localVarRequestOptions);
                const body = ObjectSerializer.deserialize(response.data, "CyborgdbServiceApiSchemasVectorsSuccessResponseModel");
                return { response: response, body: body };
            } catch (error: any) {
                if (error.response) {
                    throw new HttpError(error.response, error.response.data, error.response.status);
                }
                throw error;
            }
        });
    }

}