/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    type BinaryQueryRequest,
    BinaryQueryRequestToJSON,
} from '../models/BinaryQueryRequest';
import {
    type BinaryUpsertRequest,
    BinaryUpsertRequestToJSON,
} from '../models/BinaryUpsertRequest';
import {
    type CreateIndexRequest,
    CreateIndexRequestToJSON,
} from '../models/CreateIndexRequest';
import {
    type CreateUserRequest,
    CreateUserRequestToJSON,
} from '../models/CreateUserRequest';
import {
    type CreateUserResponse,
    CreateUserResponseFromJSON,
} from '../models/CreateUserResponse';
import {
    type CyborgdbServiceApiSchemasIndexSuccessResponseModel,
    CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSON,
} from '../models/CyborgdbServiceApiSchemasIndexSuccessResponseModel';
import {
    type CyborgdbServiceApiSchemasVectorsSuccessResponseModel,
    CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON,
} from '../models/CyborgdbServiceApiSchemasVectorsSuccessResponseModel';
import {
    type DeleteRequest,
    DeleteRequestToJSON,
} from '../models/DeleteRequest';
import {
    type GetRequest,
    GetRequestToJSON,
} from '../models/GetRequest';
import {
    type GetResponseModel,
    GetResponseModelFromJSON,
} from '../models/GetResponseModel';
import {
    type IndexInfoResponseModel,
    IndexInfoResponseModelFromJSON,
} from '../models/IndexInfoResponseModel';
import {
    type IndexListResponseModel,
    IndexListResponseModelFromJSON,
} from '../models/IndexListResponseModel';
import {
    type IndexOperationRequest,
    IndexOperationRequestToJSON,
} from '../models/IndexOperationRequest';
import {
    type IndexTrainingStatusResponseModel,
    IndexTrainingStatusResponseModelFromJSON,
} from '../models/IndexTrainingStatusResponseModel';
import {
    type ListIDsRequest,
    ListIDsRequestToJSON,
} from '../models/ListIDsRequest';
import {
    type ListIDsResponse,
    ListIDsResponseFromJSON,
} from '../models/ListIDsResponse';
import {
    type ListUsersResponse,
    ListUsersResponseFromJSON,
} from '../models/ListUsersResponse';
import {
    type QueryMetadataRequest,
    QueryMetadataRequestToJSON,
} from '../models/QueryMetadataRequest';
import {
    type QueryMetadataResponse,
    QueryMetadataResponseFromJSON,
} from '../models/QueryMetadataResponse';
import {
    type QueryResponse,
    QueryResponseFromJSON,
} from '../models/QueryResponse';
import {
    type Request,
    RequestToJSON,
} from '../models/Request';
import {
    type TrainRequest,
    TrainRequestToJSON,
} from '../models/TrainRequest';
import {
    type UpsertRequest,
    UpsertRequestToJSON,
} from '../models/UpsertRequest';
import * as runtime from '../runtime';

export interface CreateIndexV1IndexesCreatePostRequest {
    createIndexRequest: CreateIndexRequest;
}

export interface CreateUserV1IndexesIndexNameUsersPostRequest {
    indexName: string;
    createUserRequest: CreateUserRequest;
}

export interface DeleteIndexV1IndexesDeletePostRequest {
    indexOperationRequest: IndexOperationRequest;
}

export interface DeleteUserV1IndexesIndexNameUsersUserIdDeleteRequest {
    indexName: string;
    userId: string;
    xIndexKey?: string | null;
}

export interface DeleteVectorsV1VectorsDeletePostRequest {
    deleteRequest: DeleteRequest;
}

export interface GetIndexInfoV1IndexesDescribePostRequest {
    indexOperationRequest: IndexOperationRequest;
}

export interface GetIndexSizeV1VectorsNumVectorsPostRequest {
    indexOperationRequest: IndexOperationRequest;
}

export interface GetVectorsV1VectorsGetPostRequest {
    getRequest: GetRequest;
}

export interface ListIdsV1VectorsListIdsPostRequest {
    listIDsRequest: ListIDsRequest;
}

export interface ListUsersV1IndexesIndexNameUsersGetRequest {
    indexName: string;
    xIndexKey?: string | null;
}

export interface QueryMetadataV1VectorsQueryMetadataPostRequest {
    queryMetadataRequest: QueryMetadataRequest;
}

export interface QueryVectorsBinaryV1VectorsQueryBinaryPostRequest {
    binaryQueryRequest: BinaryQueryRequest;
}

export interface QueryVectorsV1VectorsQueryPostRequest {
    request: Request;
}

export interface TrainIndexV1IndexesTrainPostRequest {
    trainRequest: TrainRequest;
}

export interface UpsertVectorsBinaryV1VectorsUpsertBinaryPostRequest {
    binaryUpsertRequest: BinaryUpsertRequest;
}

export interface UpsertVectorsV1VectorsUpsertPostRequest {
    upsertRequest: UpsertRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for createIndexV1IndexesCreatePost without sending the request
     */
    async createIndexV1IndexesCreatePostRequestOpts(requestParameters: CreateIndexV1IndexesCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createIndexRequest'] == null) {
            throw new runtime.RequiredError(
                'createIndexRequest',
                'Required parameter "createIndexRequest" was null or undefined when calling createIndexV1IndexesCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIndexRequestToJSON(requestParameters['createIndexRequest']),
        };
    }

    /**
     * Create a new encrypted index with the provided configuration.  Exactly one of `kms_name` / `index_key` must be set; supplying both is rejected with 400.    * `kms_name` set — service generates a random KEK, wraps it via     the named registry slot\'s KMS, persists the envelope, and uses     the plaintext KEK as `index_key` on the core call.  CEI     generates the DEK and wraps it under that KEK internally.   * `index_key` set — SDK-supplied KEK; envelope persisted with     `provider=\"none\"`.  The SDK must re-supply `index_key` on     every subsequent request for this index.
     * Create Encrypted Index
     */
    async createIndexV1IndexesCreatePostRaw(requestParameters: CreateIndexV1IndexesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasIndexSuccessResponseModel>> {
        const requestOptions = await this.createIndexV1IndexesCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Create a new encrypted index with the provided configuration.  Exactly one of `kms_name` / `index_key` must be set; supplying both is rejected with 400.    * `kms_name` set — service generates a random KEK, wraps it via     the named registry slot\'s KMS, persists the envelope, and uses     the plaintext KEK as `index_key` on the core call.  CEI     generates the DEK and wraps it under that KEK internally.   * `index_key` set — SDK-supplied KEK; envelope persisted with     `provider=\"none\"`.  The SDK must re-supply `index_key` on     every subsequent request for this index.
     * Create Encrypted Index
     */
    async createIndexV1IndexesCreatePost(requestParameters: CreateIndexV1IndexesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasIndexSuccessResponseModel> {
        const response = await this.createIndexV1IndexesCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUserV1IndexesIndexNameUsersPost without sending the request
     */
    async createUserV1IndexesIndexNameUsersPostRequestOpts(requestParameters: CreateUserV1IndexesIndexNameUsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexName'] == null) {
            throw new runtime.RequiredError(
                'indexName',
                'Required parameter "indexName" was null or undefined when calling createUserV1IndexesIndexNameUsersPost().'
            );
        }

        if (requestParameters['createUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserRequest',
                'Required parameter "createUserRequest" was null or undefined when calling createUserV1IndexesIndexNameUsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/{index_name}/users`;
        urlPath = urlPath.replace('{index_name}', encodeURIComponent(String(requestParameters['indexName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
        };
    }

    /**
     * Mint a user API key with the given permissions, scoped to this index.  The api_key is returned once and never stored — only the user holds it.
     * Create a user for an index
     */
    async createUserV1IndexesIndexNameUsersPostRaw(requestParameters: CreateUserV1IndexesIndexNameUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUserResponse>> {
        const requestOptions = await this.createUserV1IndexesIndexNameUsersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateUserResponseFromJSON(jsonValue));
    }

    /**
     * Mint a user API key with the given permissions, scoped to this index.  The api_key is returned once and never stored — only the user holds it.
     * Create a user for an index
     */
    async createUserV1IndexesIndexNameUsersPost(requestParameters: CreateUserV1IndexesIndexNameUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUserResponse> {
        const response = await this.createUserV1IndexesIndexNameUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteIndexV1IndexesDeletePost without sending the request
     */
    async deleteIndexV1IndexesDeletePostRequestOpts(requestParameters: DeleteIndexV1IndexesDeletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexOperationRequest'] == null) {
            throw new runtime.RequiredError(
                'indexOperationRequest',
                'Required parameter "indexOperationRequest" was null or undefined when calling deleteIndexV1IndexesDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/delete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IndexOperationRequestToJSON(requestParameters['indexOperationRequest']),
        };
    }

    /**
     * Delete a specific index.  Admin-only: deleting an index drops the KMS envelope and every user\'s wrapped DEK, so it sits alongside create/train as a root operation rather than a per-user write op.
     * Delete Encrypted Index
     */
    async deleteIndexV1IndexesDeletePostRaw(requestParameters: DeleteIndexV1IndexesDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasIndexSuccessResponseModel>> {
        const requestOptions = await this.deleteIndexV1IndexesDeletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Delete a specific index.  Admin-only: deleting an index drops the KMS envelope and every user\'s wrapped DEK, so it sits alongside create/train as a root operation rather than a per-user write op.
     * Delete Encrypted Index
     */
    async deleteIndexV1IndexesDeletePost(requestParameters: DeleteIndexV1IndexesDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasIndexSuccessResponseModel> {
        const response = await this.deleteIndexV1IndexesDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteUserV1IndexesIndexNameUsersUserIdDelete without sending the request
     */
    async deleteUserV1IndexesIndexNameUsersUserIdDeleteRequestOpts(requestParameters: DeleteUserV1IndexesIndexNameUsersUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexName'] == null) {
            throw new runtime.RequiredError(
                'indexName',
                'Required parameter "indexName" was null or undefined when calling deleteUserV1IndexesIndexNameUsersUserIdDelete().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserV1IndexesIndexNameUsersUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xIndexKey'] != null) {
            headerParameters['X-Index-Key'] = String(requestParameters['xIndexKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/{index_name}/users/{user_id}`;
        urlPath = urlPath.replace('{index_name}', encodeURIComponent(String(requestParameters['indexName'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete (revoke) a user
     */
    async deleteUserV1IndexesIndexNameUsersUserIdDeleteRaw(requestParameters: DeleteUserV1IndexesIndexNameUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteUserV1IndexesIndexNameUsersUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete (revoke) a user
     */
    async deleteUserV1IndexesIndexNameUsersUserIdDelete(requestParameters: DeleteUserV1IndexesIndexNameUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserV1IndexesIndexNameUsersUserIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteVectorsV1VectorsDeletePost without sending the request
     */
    async deleteVectorsV1VectorsDeletePostRequestOpts(requestParameters: DeleteVectorsV1VectorsDeletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deleteRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteRequest',
                'Required parameter "deleteRequest" was null or undefined when calling deleteVectorsV1VectorsDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/delete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteRequestToJSON(requestParameters['deleteRequest']),
        };
    }

    /**
     * Delete vectors by their IDs.
     * Delete Items from Encrypted Index
     */
    async deleteVectorsV1VectorsDeletePostRaw(requestParameters: DeleteVectorsV1VectorsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasVectorsSuccessResponseModel>> {
        const requestOptions = await this.deleteVectorsV1VectorsDeletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Delete vectors by their IDs.
     * Delete Items from Encrypted Index
     */
    async deleteVectorsV1VectorsDeletePost(requestParameters: DeleteVectorsV1VectorsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasVectorsSuccessResponseModel> {
        const response = await this.deleteVectorsV1VectorsDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIndexInfoV1IndexesDescribePost without sending the request
     */
    async getIndexInfoV1IndexesDescribePostRequestOpts(requestParameters: GetIndexInfoV1IndexesDescribePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexOperationRequest'] == null) {
            throw new runtime.RequiredError(
                'indexOperationRequest',
                'Required parameter "indexOperationRequest" was null or undefined when calling getIndexInfoV1IndexesDescribePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/describe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IndexOperationRequestToJSON(requestParameters['indexOperationRequest']),
        };
    }

    /**
     * Get information about a specific index.
     * Describe Encrypted Index
     */
    async getIndexInfoV1IndexesDescribePostRaw(requestParameters: GetIndexInfoV1IndexesDescribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexInfoResponseModel>> {
        const requestOptions = await this.getIndexInfoV1IndexesDescribePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexInfoResponseModelFromJSON(jsonValue));
    }

    /**
     * Get information about a specific index.
     * Describe Encrypted Index
     */
    async getIndexInfoV1IndexesDescribePost(requestParameters: GetIndexInfoV1IndexesDescribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexInfoResponseModel> {
        const response = await this.getIndexInfoV1IndexesDescribePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIndexSizeV1VectorsNumVectorsPost without sending the request
     */
    async getIndexSizeV1VectorsNumVectorsPostRequestOpts(requestParameters: GetIndexSizeV1VectorsNumVectorsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexOperationRequest'] == null) {
            throw new runtime.RequiredError(
                'indexOperationRequest',
                'Required parameter "indexOperationRequest" was null or undefined when calling getIndexSizeV1VectorsNumVectorsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/num_vectors`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IndexOperationRequestToJSON(requestParameters['indexOperationRequest']),
        };
    }

    /**
     * Get the number of vectors stored in an index
     * Get the number of vectors in an index
     */
    async getIndexSizeV1VectorsNumVectorsPostRaw(requestParameters: GetIndexSizeV1VectorsNumVectorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasVectorsSuccessResponseModel>> {
        const requestOptions = await this.getIndexSizeV1VectorsNumVectorsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Get the number of vectors stored in an index
     * Get the number of vectors in an index
     */
    async getIndexSizeV1VectorsNumVectorsPost(requestParameters: GetIndexSizeV1VectorsNumVectorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasVectorsSuccessResponseModel> {
        const response = await this.getIndexSizeV1VectorsNumVectorsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTrainingStatusV1IndexesTrainingStatusGet without sending the request
     */
    async getTrainingStatusV1IndexesTrainingStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/indexes/training-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current training status including indexes being trained and the auto-train configuration.  Returns:     dict: Training status information including:         - training_indexes: List of index names currently being trained         - retrain_threshold: Vector-count floor before the first training
     * Get Training Status
     */
    async getTrainingStatusV1IndexesTrainingStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexTrainingStatusResponseModel>> {
        const requestOptions = await this.getTrainingStatusV1IndexesTrainingStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexTrainingStatusResponseModelFromJSON(jsonValue));
    }

    /**
     * Get the current training status including indexes being trained and the auto-train configuration.  Returns:     dict: Training status information including:         - training_indexes: List of index names currently being trained         - retrain_threshold: Vector-count floor before the first training
     * Get Training Status
     */
    async getTrainingStatusV1IndexesTrainingStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexTrainingStatusResponseModel> {
        const response = await this.getTrainingStatusV1IndexesTrainingStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVectorsV1VectorsGetPost without sending the request
     */
    async getVectorsV1VectorsGetPostRequestOpts(requestParameters: GetVectorsV1VectorsGetPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getRequest'] == null) {
            throw new runtime.RequiredError(
                'getRequest',
                'Required parameter "getRequest" was null or undefined when calling getVectorsV1VectorsGetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/get`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetRequestToJSON(requestParameters['getRequest']),
        };
    }

    /**
     * Retrieve vectors by their IDs.
     * Get Items from Encrypted Index
     */
    async getVectorsV1VectorsGetPostRaw(requestParameters: GetVectorsV1VectorsGetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetResponseModel>> {
        const requestOptions = await this.getVectorsV1VectorsGetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetResponseModelFromJSON(jsonValue));
    }

    /**
     * Retrieve vectors by their IDs.
     * Get Items from Encrypted Index
     */
    async getVectorsV1VectorsGetPost(requestParameters: GetVectorsV1VectorsGetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetResponseModel> {
        const response = await this.getVectorsV1VectorsGetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthCheckV1HealthGet without sending the request
     */
    async healthCheckV1HealthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check if the API is running.
     * Health check endpoint
     */
    async healthCheckV1HealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.healthCheckV1HealthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Check if the API is running.
     * Health check endpoint
     */
    async healthCheckV1HealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.healthCheckV1HealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listIdsV1VectorsListIdsPost without sending the request
     */
    async listIdsV1VectorsListIdsPostRequestOpts(requestParameters: ListIdsV1VectorsListIdsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listIDsRequest'] == null) {
            throw new runtime.RequiredError(
                'listIDsRequest',
                'Required parameter "listIDsRequest" was null or undefined when calling listIdsV1VectorsListIdsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/list_ids`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListIDsRequestToJSON(requestParameters['listIDsRequest']),
        };
    }

    /**
     * List all item IDs currently stored in the index.  Returns a list of all IDs and the total count.
     * List all IDs in an index
     */
    async listIdsV1VectorsListIdsPostRaw(requestParameters: ListIdsV1VectorsListIdsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListIDsResponse>> {
        const requestOptions = await this.listIdsV1VectorsListIdsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListIDsResponseFromJSON(jsonValue));
    }

    /**
     * List all item IDs currently stored in the index.  Returns a list of all IDs and the total count.
     * List all IDs in an index
     */
    async listIdsV1VectorsListIdsPost(requestParameters: ListIdsV1VectorsListIdsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListIDsResponse> {
        const response = await this.listIdsV1VectorsListIdsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listIndexesV1IndexesListGet without sending the request
     */
    async listIndexesV1IndexesListGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all available indexes.
     * List Encrypted Indexes
     */
    async listIndexesV1IndexesListGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexListResponseModel>> {
        const requestOptions = await this.listIndexesV1IndexesListGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexListResponseModelFromJSON(jsonValue));
    }

    /**
     * List all available indexes.
     * List Encrypted Indexes
     */
    async listIndexesV1IndexesListGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexListResponseModel> {
        const response = await this.listIndexesV1IndexesListGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listUsersV1IndexesIndexNameUsersGet without sending the request
     */
    async listUsersV1IndexesIndexNameUsersGetRequestOpts(requestParameters: ListUsersV1IndexesIndexNameUsersGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['indexName'] == null) {
            throw new runtime.RequiredError(
                'indexName',
                'Required parameter "indexName" was null or undefined when calling listUsersV1IndexesIndexNameUsersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xIndexKey'] != null) {
            headerParameters['X-Index-Key'] = String(requestParameters['xIndexKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/{index_name}/users`;
        urlPath = urlPath.replace('{index_name}', encodeURIComponent(String(requestParameters['indexName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List an index\'s users
     */
    async listUsersV1IndexesIndexNameUsersGetRaw(requestParameters: ListUsersV1IndexesIndexNameUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListUsersResponse>> {
        const requestOptions = await this.listUsersV1IndexesIndexNameUsersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListUsersResponseFromJSON(jsonValue));
    }

    /**
     * List an index\'s users
     */
    async listUsersV1IndexesIndexNameUsersGet(requestParameters: ListUsersV1IndexesIndexNameUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListUsersResponse> {
        const response = await this.listUsersV1IndexesIndexNameUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryMetadataV1VectorsQueryMetadataPost without sending the request
     */
    async queryMetadataV1VectorsQueryMetadataPostRequestOpts(requestParameters: QueryMetadataV1VectorsQueryMetadataPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['queryMetadataRequest'] == null) {
            throw new runtime.RequiredError(
                'queryMetadataRequest',
                'Required parameter "queryMetadataRequest" was null or undefined when calling queryMetadataV1VectorsQueryMetadataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/query_metadata`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryMetadataRequestToJSON(requestParameters['queryMetadataRequest']),
        };
    }

    /**
     * Find items by metadata alone — no query vector.  With no `text`, resolves the filter entirely from the encrypted metadata index and returns the matching items, unscored. With `text`, runs BM25 over the index\'s full_text fields and returns the top matches ranked by score; a filter given alongside acts as a pre-filter. Works on untrained indexes.  Because there is no post-filter stage to fall back on, the index\'s `metadata_schema` is enforced here: `$regex` / `$contains` need a `pattern` field, and a `filterable: false` field cannot be filtered on. Both come back as 400 with the reason. `/query` with a vector has no such restriction.
     * Query an Encrypted Index by Metadata Only
     */
    async queryMetadataV1VectorsQueryMetadataPostRaw(requestParameters: QueryMetadataV1VectorsQueryMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryMetadataResponse>> {
        const requestOptions = await this.queryMetadataV1VectorsQueryMetadataPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Find items by metadata alone — no query vector.  With no `text`, resolves the filter entirely from the encrypted metadata index and returns the matching items, unscored. With `text`, runs BM25 over the index\'s full_text fields and returns the top matches ranked by score; a filter given alongside acts as a pre-filter. Works on untrained indexes.  Because there is no post-filter stage to fall back on, the index\'s `metadata_schema` is enforced here: `$regex` / `$contains` need a `pattern` field, and a `filterable: false` field cannot be filtered on. Both come back as 400 with the reason. `/query` with a vector has no such restriction.
     * Query an Encrypted Index by Metadata Only
     */
    async queryMetadataV1VectorsQueryMetadataPost(requestParameters: QueryMetadataV1VectorsQueryMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryMetadataResponse> {
        const response = await this.queryMetadataV1VectorsQueryMetadataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryVectorsBinaryV1VectorsQueryBinaryPost without sending the request
     */
    async queryVectorsBinaryV1VectorsQueryBinaryPostRequestOpts(requestParameters: QueryVectorsBinaryV1VectorsQueryBinaryPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['binaryQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'binaryQueryRequest',
                'Required parameter "binaryQueryRequest" was null or undefined when calling queryVectorsBinaryV1VectorsQueryBinaryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/query_binary`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BinaryQueryRequestToJSON(requestParameters['binaryQueryRequest']),
        };
    }

    /**
     * Search for nearest neighbors using binary format for query vectors.  This endpoint is optimized for large batch queries. Query vectors are sent as base64-encoded float32 numpy arrays, which is more efficient than JSON arrays for large batches.
     * Query Encrypted Index (Binary Format)
     */
    async queryVectorsBinaryV1VectorsQueryBinaryPostRaw(requestParameters: QueryVectorsBinaryV1VectorsQueryBinaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        const requestOptions = await this.queryVectorsBinaryV1VectorsQueryBinaryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Search for nearest neighbors using binary format for query vectors.  This endpoint is optimized for large batch queries. Query vectors are sent as base64-encoded float32 numpy arrays, which is more efficient than JSON arrays for large batches.
     * Query Encrypted Index (Binary Format)
     */
    async queryVectorsBinaryV1VectorsQueryBinaryPost(requestParameters: QueryVectorsBinaryV1VectorsQueryBinaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.queryVectorsBinaryV1VectorsQueryBinaryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryVectorsV1VectorsQueryPost without sending the request
     */
    async queryVectorsV1VectorsQueryPostRequestOpts(requestParameters: QueryVectorsV1VectorsQueryPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling queryVectorsV1VectorsQueryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/query`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Search for nearest neighbors in the index.
     * Query Encrypted Index
     */
    async queryVectorsV1VectorsQueryPostRaw(requestParameters: QueryVectorsV1VectorsQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        const requestOptions = await this.queryVectorsV1VectorsQueryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Search for nearest neighbors in the index.
     * Query Encrypted Index
     */
    async queryVectorsV1VectorsQueryPost(requestParameters: QueryVectorsV1VectorsQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.queryVectorsV1VectorsQueryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for trainIndexV1IndexesTrainPost without sending the request
     */
    async trainIndexV1IndexesTrainPostRequestOpts(requestParameters: TrainIndexV1IndexesTrainPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainRequest'] == null) {
            throw new runtime.RequiredError(
                'trainRequest',
                'Required parameter "trainRequest" was null or undefined when calling trainIndexV1IndexesTrainPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/indexes/train`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainRequestToJSON(requestParameters['trainRequest']),
        };
    }

    /**
     * Train the index for efficient querying.  Training is queued and processed asynchronously. If the index is already being trained or queued, returns the current status.
     * Train Encrypted index
     */
    async trainIndexV1IndexesTrainPostRaw(requestParameters: TrainIndexV1IndexesTrainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasIndexSuccessResponseModel>> {
        const requestOptions = await this.trainIndexV1IndexesTrainPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Train the index for efficient querying.  Training is queued and processed asynchronously. If the index is already being trained or queued, returns the current status.
     * Train Encrypted index
     */
    async trainIndexV1IndexesTrainPost(requestParameters: TrainIndexV1IndexesTrainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasIndexSuccessResponseModel> {
        const response = await this.trainIndexV1IndexesTrainPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertVectorsBinaryV1VectorsUpsertBinaryPost without sending the request
     */
    async upsertVectorsBinaryV1VectorsUpsertBinaryPostRequestOpts(requestParameters: UpsertVectorsBinaryV1VectorsUpsertBinaryPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['binaryUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'binaryUpsertRequest',
                'Required parameter "binaryUpsertRequest" was null or undefined when calling upsertVectorsBinaryV1VectorsUpsertBinaryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/upsert_binary`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BinaryUpsertRequestToJSON(requestParameters['binaryUpsertRequest']),
        };
    }

    /**
     * Add or update vectors in the index using binary format.  This endpoint is optimized for large batches of vectors. Vectors are sent as base64-encoded float32 numpy arrays, which is much more efficient than JSON arrays for large datasets.  After upserting, checks if the index needs training/retraining based on the number of vectors and triggers automatic training if needed.
     * Add Items to Encrypted Index (Binary Format)
     */
    async upsertVectorsBinaryV1VectorsUpsertBinaryPostRaw(requestParameters: UpsertVectorsBinaryV1VectorsUpsertBinaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasVectorsSuccessResponseModel>> {
        const requestOptions = await this.upsertVectorsBinaryV1VectorsUpsertBinaryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Add or update vectors in the index using binary format.  This endpoint is optimized for large batches of vectors. Vectors are sent as base64-encoded float32 numpy arrays, which is much more efficient than JSON arrays for large datasets.  After upserting, checks if the index needs training/retraining based on the number of vectors and triggers automatic training if needed.
     * Add Items to Encrypted Index (Binary Format)
     */
    async upsertVectorsBinaryV1VectorsUpsertBinaryPost(requestParameters: UpsertVectorsBinaryV1VectorsUpsertBinaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasVectorsSuccessResponseModel> {
        const response = await this.upsertVectorsBinaryV1VectorsUpsertBinaryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertVectorsV1VectorsUpsertPost without sending the request
     */
    async upsertVectorsV1VectorsUpsertPostRequestOpts(requestParameters: UpsertVectorsV1VectorsUpsertPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['upsertRequest'] == null) {
            throw new runtime.RequiredError(
                'upsertRequest',
                'Required parameter "upsertRequest" was null or undefined when calling upsertVectorsV1VectorsUpsertPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/v1/vectors/upsert`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertRequestToJSON(requestParameters['upsertRequest']),
        };
    }

    /**
     * Add or update vectors in the index.  After upserting, checks if the index needs training/retraining based on the number of vectors and triggers automatic training if needed.
     * Add Items to Encrypted Index
     */
    async upsertVectorsV1VectorsUpsertPostRaw(requestParameters: UpsertVectorsV1VectorsUpsertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CyborgdbServiceApiSchemasVectorsSuccessResponseModel>> {
        const requestOptions = await this.upsertVectorsV1VectorsUpsertPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON(jsonValue));
    }

    /**
     * Add or update vectors in the index.  After upserting, checks if the index needs training/retraining based on the number of vectors and triggers automatic training if needed.
     * Add Items to Encrypted Index
     */
    async upsertVectorsV1VectorsUpsertPost(requestParameters: UpsertVectorsV1VectorsUpsertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CyborgdbServiceApiSchemasVectorsSuccessResponseModel> {
        const response = await this.upsertVectorsV1VectorsUpsertPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
