/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BinaryVectorBatch } from './BinaryVectorBatch';
import {
    BinaryVectorBatchFromJSON,
    BinaryVectorBatchFromJSONTyped,
    BinaryVectorBatchToJSON,
    BinaryVectorBatchToJSONTyped,
} from './BinaryVectorBatch';

/**
 * Request model for adding or updating vectors using binary format.
 * 
 * This is more efficient than UpsertRequest for large batches as vectors
 * are sent as base64-encoded binary data instead of JSON arrays.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     batch (BinaryVectorBatch): The batch of vectors in binary format.
 * @export
 * @interface BinaryUpsertRequest
 */
export interface BinaryUpsertRequest {
    /**
     * 
     * @type {BinaryVectorBatch}
     * @memberof BinaryUpsertRequest
     */
    batch: BinaryVectorBatch;
    /**
     * 
     * @type {string}
     * @memberof BinaryUpsertRequest
     */
    indexKey?: string | null;
    /**
     * ID name
     * @type {string}
     * @memberof BinaryUpsertRequest
     */
    indexName: string;
}

/**
 * Check if a given object implements the BinaryUpsertRequest interface.
 */
export function instanceOfBinaryUpsertRequest(value: object): value is BinaryUpsertRequest {
    if (!('batch' in value) || value['batch'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function BinaryUpsertRequestFromJSON(json: any): BinaryUpsertRequest {
    return BinaryUpsertRequestFromJSONTyped(json, false);
}

export function BinaryUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'batch': BinaryVectorBatchFromJSON(json['batch']),
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'indexName': json['index_name'],
    };
}

export function BinaryUpsertRequestToJSON(json: any): BinaryUpsertRequest {
    return BinaryUpsertRequestToJSONTyped(json, false);
}

export function BinaryUpsertRequestToJSONTyped(value?: BinaryUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batch': BinaryVectorBatchToJSON(value['batch']),
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
    };
}

