/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BinaryQueryBatch } from './BinaryQueryBatch';
import {
    BinaryQueryBatchFromJSON,
    BinaryQueryBatchToJSON,
} from './BinaryQueryBatch';

/**
 * Request model for batch similarity search using binary format.
 * 
 * This is more efficient than BatchQueryRequest for large batches as vectors
 * are sent as base64-encoded binary data instead of JSON arrays.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 *     HybridQueryParams: `text` and the fusion knobs for hybrid search.
 * 
 * Attributes:
 *     batch (BinaryQueryBatch): The batch of query vectors in binary format.
 *     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.
 *     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.
 *     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.
 *     rerank_mult (Optional[int]): Multiplier for stage 1 retrieval in reranking indexes. Defaults to 10.
 *     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like
 *         dictionary (see `FILTERS_DESCRIPTION` for the operator set).
 *         Defaults to {}.
 *     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
 * @export
 * @interface BinaryQueryRequest
 */
export interface BinaryQueryRequest {
    /**
     * Query text for a BM25 full-text leg. Requires an index with at least one full_text field. Omitted/empty leaves the query text-free.
     * @type {string}
     * @memberof BinaryQueryRequest
     */
    text?: string | null;
    /**
     * full_text fields the text leg searches; omitted means all of them. Naming a non-full_text field raises.
     * @type {Array<string>}
     * @memberof BinaryQueryRequest
     */
    textFields?: Array<string> | null;
    /**
     * Per-field weights on the summed per-field BM25 scores, parallel to the searched fields. Omitted means 1.0 each.
     * @type {Array<number>}
     * @memberof BinaryQueryRequest
     */
    textFieldWeights?: Array<number> | null;
    /**
     * Require every query term to match (AND) instead of any (OR, the default).
     * @type {boolean}
     * @memberof BinaryQueryRequest
     */
    requireAllTerms?: boolean | null;
    /**
     * Leg blend in [0, 1]: 0 = pure BM25, 1 = pure vector; omitted means 0.5. An exact endpoint skips the dead leg's retrieval.
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    alpha?: number | null;
    /**
     * RRF rank-smoothing constant (> 0; omitted means 60). Higher rewards agreement further down each leg's list.
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    rrfK?: number | null;
    /**
     * Per-leg candidate depth as a multiple of top_k (>= 1; omitted means 3), so each leg looks deeper than the final cut.
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    windowMult?: number | null;
    /**
     * ID name
     * @type {string}
     * @memberof BinaryQueryRequest
     */
    indexName: string;
    /**
     * 32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).
     * @type {string}
     * @memberof BinaryQueryRequest
     */
    indexKey?: string | null;
    /**
     * 
     * @type {BinaryQueryBatch}
     * @memberof BinaryQueryRequest
     */
    batch: BinaryQueryBatch;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    topK?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    nProbes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    rerankMult?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BinaryQueryRequest
     */
    greedy?: boolean | null;
    /**
     * Metadata filters as a JSON object. Operators: `$eq`, `$ne`, `$in`, `$nin`, `$exists`, `$gt`, `$gte`, `$lt`, `$lte`, `$regex`, `$contains`, combined with `$and` / `$or` / `$nor` / `$not`. Filtering works on any metadata field; the index's `metadata_schema` only decides how a filter is resolved — fields marked `filterable` (the default) are answered from the inverted index, and `$regex` / `$contains` are answered from the regex dictionary on `pattern` fields. Anything else falls back to a post-filter over the decrypted metadata, which is correct but slower. Dates have no native type: store and filter them as epoch milliseconds.
     * @type {{ [key: string]: any; }}
     * @memberof BinaryQueryRequest
     */
    filters?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BinaryQueryRequest
     */
    include?: Array<string>;
}

/**
 * Check if a given object implements the BinaryQueryRequest interface.
 */
export function instanceOfBinaryQueryRequest(value: object): value is BinaryQueryRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('batch' in value) || value['batch'] === undefined) return false;
    return true;
}

export function BinaryQueryRequestFromJSON(json: any): BinaryQueryRequest {
    return BinaryQueryRequestFromJSONTyped(json, false);
}

export function BinaryQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'textFields': json['text_fields'] == null ? undefined : json['text_fields'],
        'textFieldWeights': json['text_field_weights'] == null ? undefined : json['text_field_weights'],
        'requireAllTerms': json['require_all_terms'] == null ? undefined : json['require_all_terms'],
        'alpha': json['alpha'] == null ? undefined : json['alpha'],
        'rrfK': json['rrf_k'] == null ? undefined : json['rrf_k'],
        'windowMult': json['window_mult'] == null ? undefined : json['window_mult'],
        'indexName': json['index_name'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'batch': BinaryQueryBatchFromJSON(json['batch']),
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'nProbes': json['n_probes'] == null ? undefined : json['n_probes'],
        'rerankMult': json['rerank_mult'] == null ? undefined : json['rerank_mult'],
        'greedy': json['greedy'] == null ? undefined : json['greedy'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'include': json['include'] == null ? undefined : json['include'],
    };
}

export function BinaryQueryRequestToJSON(json: any): BinaryQueryRequest {
    return BinaryQueryRequestToJSONTyped(json, false);
}

export function BinaryQueryRequestToJSONTyped(value?: BinaryQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'text_fields': value['textFields'],
        'text_field_weights': value['textFieldWeights'],
        'require_all_terms': value['requireAllTerms'],
        'alpha': value['alpha'],
        'rrf_k': value['rrfK'],
        'window_mult': value['windowMult'],
        'index_name': value['indexName'],
        'index_key': value['indexKey'],
        'batch': BinaryQueryBatchToJSON(value['batch']),
        'top_k': value['topK'],
        'n_probes': value['nProbes'],
        'rerank_mult': value['rerankMult'],
        'greedy': value['greedy'],
        'filters': value['filters'],
        'include': value['include'],
    };
}

