/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BinaryVectorBatchContentsInner } from './BinaryVectorBatchContentsInner';
import {
    BinaryVectorBatchContentsInnerFromJSON,
    BinaryVectorBatchContentsInnerFromJSONTyped,
    BinaryVectorBatchContentsInnerToJSON,
    BinaryVectorBatchContentsInnerToJSONTyped,
} from './BinaryVectorBatchContentsInner';

/**
 * Represents a batch of vectors in binary format for efficient transfer.
 * 
 * Attributes:
 *     ids (List[str]): List of unique identifiers for each vector.
 *     vectors_b64 (str): Base64-encoded float32 numpy array (shape: n_vectors x dimension).
 *     dimension (int): The dimension of each vector.
 *     metadata (Optional[List[Optional[Dict[str, Any]]]]): Optional metadata for each vector.
 *     contents (Optional[List[Optional[Union[str, bytes]]]]): Optional contents for each vector.
 * @export
 * @interface BinaryVectorBatch
 */
export interface BinaryVectorBatch {
    /**
     * 
     * @type {Array<string>}
     * @memberof BinaryVectorBatch
     */
    ids: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BinaryVectorBatch
     */
    vectorsB64: string;
    /**
     * 
     * @type {number}
     * @memberof BinaryVectorBatch
     */
    dimension: number;
    /**
     * 
     * @type {Array<{ [key: string]: any; } | null>}
     * @memberof BinaryVectorBatch
     */
    metadata?: Array<{ [key: string]: any; } | null> | null;
    /**
     * 
     * @type {Array<BinaryVectorBatchContentsInner>}
     * @memberof BinaryVectorBatch
     */
    contents?: Array<BinaryVectorBatchContentsInner> | null;
}

/**
 * Check if a given object implements the BinaryVectorBatch interface.
 */
export function instanceOfBinaryVectorBatch(value: object): value is BinaryVectorBatch {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    if (!('vectorsB64' in value) || value['vectorsB64'] === undefined) return false;
    if (!('dimension' in value) || value['dimension'] === undefined) return false;
    return true;
}

export function BinaryVectorBatchFromJSON(json: any): BinaryVectorBatch {
    return BinaryVectorBatchFromJSONTyped(json, false);
}

export function BinaryVectorBatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryVectorBatch {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'vectorsB64': json['vectors_b64'],
        'dimension': json['dimension'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'contents': json['contents'] == null ? undefined : ((json['contents'] as Array<any>).map(BinaryVectorBatchContentsInnerFromJSON)),
    };
}

export function BinaryVectorBatchToJSON(json: any): BinaryVectorBatch {
    return BinaryVectorBatchToJSONTyped(json, false);
}

export function BinaryVectorBatchToJSONTyped(value?: BinaryVectorBatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
        'vectors_b64': value['vectorsB64'],
        'dimension': value['dimension'],
        'metadata': value['metadata'],
        'contents': value['contents'] == null ? undefined : ((value['contents'] as Array<any>).map(BinaryVectorBatchContentsInnerToJSON)),
    };
}

