/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BinaryQueryBatch } from './BinaryQueryBatch';
import {
    BinaryQueryBatchFromJSON,
    BinaryQueryBatchFromJSONTyped,
    BinaryQueryBatchToJSON,
    BinaryQueryBatchToJSONTyped,
} from './BinaryQueryBatch';

/**
 * Request model for batch similarity search using binary format.
 * 
 * This is more efficient than BatchQueryRequest for large batches as vectors
 * are sent as base64-encoded binary data instead of JSON arrays.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     batch (BinaryQueryBatch): The batch of query vectors in binary format.
 *     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.
 *     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.
 *     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.
 *     filters (Optional[Dict[str, Any]]): JSON-like dictionary specifying metadata filters. Defaults to {}.
 *     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
 * @export
 * @interface BinaryQueryRequest
 */
export interface BinaryQueryRequest {
    /**
     * 32-byte encryption key as hex string
     * @type {string}
     * @memberof BinaryQueryRequest
     */
    indexKey: string;
    /**
     * ID name
     * @type {string}
     * @memberof BinaryQueryRequest
     */
    indexName: string;
    /**
     * 
     * @type {BinaryQueryBatch}
     * @memberof BinaryQueryRequest
     */
    batch: BinaryQueryBatch;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    topK?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryRequest
     */
    nProbes?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BinaryQueryRequest
     */
    greedy?: boolean | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BinaryQueryRequest
     */
    filters?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BinaryQueryRequest
     */
    include?: Array<string>;
}

/**
 * Check if a given object implements the BinaryQueryRequest interface.
 */
export function instanceOfBinaryQueryRequest(value: object): value is BinaryQueryRequest {
    if (!('indexKey' in value) || value['indexKey'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('batch' in value) || value['batch'] === undefined) return false;
    return true;
}

export function BinaryQueryRequestFromJSON(json: any): BinaryQueryRequest {
    return BinaryQueryRequestFromJSONTyped(json, false);
}

export function BinaryQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexKey': json['index_key'],
        'indexName': json['index_name'],
        'batch': BinaryQueryBatchFromJSON(json['batch']),
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'nProbes': json['n_probes'] == null ? undefined : json['n_probes'],
        'greedy': json['greedy'] == null ? undefined : json['greedy'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'include': json['include'] == null ? undefined : json['include'],
    };
}

export function BinaryQueryRequestToJSON(json: any): BinaryQueryRequest {
    return BinaryQueryRequestToJSONTyped(json, false);
}

export function BinaryQueryRequestToJSONTyped(value?: BinaryQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
        'batch': BinaryQueryBatchToJSON(value['batch']),
        'top_k': value['topK'],
        'n_probes': value['nProbes'],
        'greedy': value['greedy'],
        'filters': value['filters'],
        'include': value['include'],
    };
}

