/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BinaryVectorBatchContentsInner
 */
export interface BinaryVectorBatchContentsInner {
}

/**
 * Check if a given object implements the BinaryVectorBatchContentsInner interface.
 */
export function instanceOfBinaryVectorBatchContentsInner(value: object): value is BinaryVectorBatchContentsInner {
    return true;
}

export function BinaryVectorBatchContentsInnerFromJSON(json: any): BinaryVectorBatchContentsInner {
    return BinaryVectorBatchContentsInnerFromJSONTyped(json, false);
}

export function BinaryVectorBatchContentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryVectorBatchContentsInner {
    return json;
}

export function BinaryVectorBatchContentsInnerToJSON(json: any): BinaryVectorBatchContentsInner {
    return BinaryVectorBatchContentsInnerToJSONTyped(json, false);
}

export function BinaryVectorBatchContentsInnerToJSONTyped(value?: BinaryVectorBatchContentsInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

