/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a batch of query vectors in binary format for efficient transfer.
 * 
 * Attributes:
 *     vectors_b64 (str): Base64-encoded float32 numpy array (shape: n_queries x dimension).
 *     dimension (int): The dimension of each vector.
 * @export
 * @interface BinaryQueryBatch
 */
export interface BinaryQueryBatch {
    /**
     * 
     * @type {string}
     * @memberof BinaryQueryBatch
     */
    vectorsB64: string;
    /**
     * 
     * @type {number}
     * @memberof BinaryQueryBatch
     */
    dimension: number;
}

/**
 * Check if a given object implements the BinaryQueryBatch interface.
 */
export function instanceOfBinaryQueryBatch(value: object): value is BinaryQueryBatch {
    if (!('vectorsB64' in value) || value['vectorsB64'] === undefined) return false;
    if (!('dimension' in value) || value['dimension'] === undefined) return false;
    return true;
}

export function BinaryQueryBatchFromJSON(json: any): BinaryQueryBatch {
    return BinaryQueryBatchFromJSONTyped(json, false);
}

export function BinaryQueryBatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryQueryBatch {
    if (json == null) {
        return json;
    }
    return {
        
        'vectorsB64': json['vectors_b64'],
        'dimension': json['dimension'],
    };
}

export function BinaryQueryBatchToJSON(json: any): BinaryQueryBatch {
    return BinaryQueryBatchToJSONTyped(json, false);
}

export function BinaryQueryBatchToJSONTyped(value?: BinaryQueryBatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vectors_b64': value['vectorsB64'],
        'dimension': value['dimension'],
    };
}

