/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-keystore RAM caching policy. Each field opts a keystore into the
 * in-memory cache. Fields left as None fall back to cyborgdb-core's default
 * (cache nothing).
 * @export
 * @interface CachePolicyModel
 */
export interface CachePolicyModel {
    /**
     * 
     * @type {boolean}
     * @memberof CachePolicyModel
     */
    vectors?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CachePolicyModel
     */
    metadata?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CachePolicyModel
     */
    ids?: boolean | null;
}

/**
 * Check if a given object implements the CachePolicyModel interface.
 */
export function instanceOfCachePolicyModel(value: object): value is CachePolicyModel {
    return true;
}

export function CachePolicyModelFromJSON(json: any): CachePolicyModel {
    return CachePolicyModelFromJSONTyped(json, false);
}

export function CachePolicyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CachePolicyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'vectors': json['vectors'] == null ? undefined : json['vectors'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function CachePolicyModelToJSON(json: any): CachePolicyModel {
    return CachePolicyModelToJSONTyped(json, false);
}

export function CachePolicyModelToJSONTyped(value?: CachePolicyModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vectors': value['vectors'],
        'metadata': value['metadata'],
        'ids': value['ids'],
    };
}

