/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Contents
 */
export interface Contents {
}

/**
 * Check if a given object implements the Contents interface.
 */
export function instanceOfContents(value: object): value is Contents {
    return true;
}

export function ContentsFromJSON(json: any): Contents {
    return ContentsFromJSONTyped(json, false);
}

export function ContentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contents {
    return json;
}

export function ContentsToJSON(json: any): Contents {
    return ContentsToJSONTyped(json, false);
}

export function ContentsToJSONTyped(value?: Contents | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

