/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.16.3.dev86
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating a new encrypted DiskIVF index.
 * 
 * Exactly one of `kms_name` / `index_key` must be supplied; supplying
 * both is rejected with 400.
 * 
 * Attributes:
 *     index_name: The name/identifier of the index.
 *     kms_name: Name of a `kms.registry` entry in the service YAML.
 *         When supplied (and `index_key` is omitted), the service
 *         generates the KEK itself, wraps it under that entry's KMS,
 *         and persists the envelope.
 *     index_key: A 32-byte encryption key as a hex string.  When
 *         supplied (and `kms_name` is omitted), the SDK provides the
 *         KEK directly and the persisted envelope records
 *         `provider="none"`.
 *     dimension (Optional[int]): Dimensionality of the vectors. Auto-detected
 *         from the first upsert if omitted.
 *     embedding_model (Optional[str]): Optional embedding model name.
 *     metric (Optional[str]): Optional distance metric.
 *     storage_precision (Optional[Literal["float32", "float16"]]): On-disk
 *         rerank-vector dtype. Defaults to float32 in core.
 * @export
 * @interface CreateIndexRequest
 */
export interface CreateIndexRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateIndexRequest
     */
    dimension?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    embeddingModel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    indexKey?: string | null;
    /**
     * ID name
     * @type {string}
     * @memberof CreateIndexRequest
     */
    indexName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    kmsName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    metric?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    storagePrecision?: CreateIndexRequestStoragePrecisionEnum | null;
}


/**
 * @export
 */
export const CreateIndexRequestStoragePrecisionEnum = {
    Float32: 'float32',
    Float16: 'float16'
} as const;
export type CreateIndexRequestStoragePrecisionEnum = typeof CreateIndexRequestStoragePrecisionEnum[keyof typeof CreateIndexRequestStoragePrecisionEnum];


/**
 * Check if a given object implements the CreateIndexRequest interface.
 */
export function instanceOfCreateIndexRequest(value: object): value is CreateIndexRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function CreateIndexRequestFromJSON(json: any): CreateIndexRequest {
    return CreateIndexRequestFromJSONTyped(json, false);
}

export function CreateIndexRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndexRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dimension': json['dimension'] == null ? undefined : json['dimension'],
        'embeddingModel': json['embedding_model'] == null ? undefined : json['embedding_model'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'indexName': json['index_name'],
        'kmsName': json['kms_name'] == null ? undefined : json['kms_name'],
        'metric': json['metric'] == null ? undefined : json['metric'],
        'storagePrecision': json['storage_precision'] == null ? undefined : json['storage_precision'],
    };
}

export function CreateIndexRequestToJSON(json: any): CreateIndexRequest {
    return CreateIndexRequestToJSONTyped(json, false);
}

export function CreateIndexRequestToJSONTyped(value?: CreateIndexRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dimension': value['dimension'],
        'embedding_model': value['embeddingModel'],
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
        'kms_name': value['kmsName'],
        'metric': value['metric'],
        'storage_precision': value['storagePrecision'],
    };
}

