/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request model for minting a user API key scoped to one index.
 * 
 * Attributes:
 *     permissions (List[str]): Subset of {"read", "write"}; at least one.
 *     index_key (Optional[str]): Index KEK (hex) for SDK-supplied indexes.
 *         Omit for KMS-backed indexes — the service resolves the KEK server-side.
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * Subset of {"read", "write"}; at least one.
     * @type {Array<string>}
     * @memberof CreateUserRequest
     */
    permissions: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    indexKey?: string | null;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): value is CreateUserRequest {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
    return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': json['permissions'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
    };
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
    return CreateUserRequestToJSONTyped(json, false);
}

export function CreateUserRequestToJSONTyped(value?: CreateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': value['permissions'],
        'index_key': value['indexKey'],
    };
}

