/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard success response model for operations like upsert and delete.
 * 
 * Attributes:
 *     status (str): Operation status. Defaults to `"success"`.
 *     message (str): Descriptive success message.
 * @export
 * @interface CyborgdbServiceApiSchemasVectorsSuccessResponseModel
 */
export interface CyborgdbServiceApiSchemasVectorsSuccessResponseModel {
    /**
     * 
     * @type {string}
     * @memberof CyborgdbServiceApiSchemasVectorsSuccessResponseModel
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CyborgdbServiceApiSchemasVectorsSuccessResponseModel
     */
    message: string;
}

/**
 * Check if a given object implements the CyborgdbServiceApiSchemasVectorsSuccessResponseModel interface.
 */
export function instanceOfCyborgdbServiceApiSchemasVectorsSuccessResponseModel(value: object): value is CyborgdbServiceApiSchemasVectorsSuccessResponseModel {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSON(json: any): CyborgdbServiceApiSchemasVectorsSuccessResponseModel {
    return CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSONTyped(json, false);
}

export function CyborgdbServiceApiSchemasVectorsSuccessResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CyborgdbServiceApiSchemasVectorsSuccessResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'],
    };
}

export function CyborgdbServiceApiSchemasVectorsSuccessResponseModelToJSON(json: any): CyborgdbServiceApiSchemasVectorsSuccessResponseModel {
    return CyborgdbServiceApiSchemasVectorsSuccessResponseModelToJSONTyped(json, false);
}

export function CyborgdbServiceApiSchemasVectorsSuccessResponseModelToJSONTyped(value?: CyborgdbServiceApiSchemasVectorsSuccessResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

