/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard success response model.
 * 
 * Attributes:
 *     status (str): The status of the response. Defaults to "success".
 *     message (str): A success message.
 * @export
 * @interface CyborgdbServiceApiSchemasIndexSuccessResponseModel
 */
export interface CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    /**
     * 
     * @type {string}
     * @memberof CyborgdbServiceApiSchemasIndexSuccessResponseModel
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof CyborgdbServiceApiSchemasIndexSuccessResponseModel
     */
    status?: string;
}

/**
 * Check if a given object implements the CyborgdbServiceApiSchemasIndexSuccessResponseModel interface.
 */
export function instanceOfCyborgdbServiceApiSchemasIndexSuccessResponseModel(value: object): value is CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSON(json: any): CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    return CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSONTyped(json, false);
}

export function CyborgdbServiceApiSchemasIndexSuccessResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CyborgdbServiceApiSchemasIndexSuccessResponseModelToJSON(json: any): CyborgdbServiceApiSchemasIndexSuccessResponseModel {
    return CyborgdbServiceApiSchemasIndexSuccessResponseModelToJSONTyped(json, false);
}

export function CyborgdbServiceApiSchemasIndexSuccessResponseModelToJSONTyped(value?: CyborgdbServiceApiSchemasIndexSuccessResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

