/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for deleting vectors from the encrypted index.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     ids (List[str]): List of vector item IDs to be deleted.
 * @export
 * @interface DeleteRequest
 */
export interface DeleteRequest {
    /**
     * 32-byte encryption key as hex string
     * @type {string}
     * @memberof DeleteRequest
     */
    indexKey: string;
    /**
     * ID name
     * @type {string}
     * @memberof DeleteRequest
     */
    indexName: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteRequest
     */
    ids: Array<string>;
}

/**
 * Check if a given object implements the DeleteRequest interface.
 */
export function instanceOfDeleteRequest(value: object): value is DeleteRequest {
    if (!('indexKey' in value) || value['indexKey'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function DeleteRequestFromJSON(json: any): DeleteRequest {
    return DeleteRequestFromJSONTyped(json, false);
}

export function DeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexKey': json['index_key'],
        'indexName': json['index_name'],
        'ids': json['ids'],
    };
}

export function DeleteRequestToJSON(json: any): DeleteRequest {
    return DeleteRequestToJSONTyped(json, false);
}

export function DeleteRequestToJSONTyped(value?: DeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
        'ids': value['ids'],
    };
}

