/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetResultItemModel } from './GetResultItemModel';
import {
    GetResultItemModelFromJSON,
    GetResultItemModelFromJSONTyped,
    GetResultItemModelToJSON,
    GetResultItemModelToJSONTyped,
} from './GetResultItemModel';

/**
 * Response model for retrieving multiple encrypted index items.
 * 
 * Attributes:
 *     results (List[GetResultItem]): A list of retrieved items with requested fields.
 * @export
 * @interface GetResponseModel
 */
export interface GetResponseModel {
    /**
     * 
     * @type {Array<GetResultItemModel>}
     * @memberof GetResponseModel
     */
    results: Array<GetResultItemModel>;
}

/**
 * Check if a given object implements the GetResponseModel interface.
 */
export function instanceOfGetResponseModel(value: object): value is GetResponseModel {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function GetResponseModelFromJSON(json: any): GetResponseModel {
    return GetResponseModelFromJSONTyped(json, false);
}

export function GetResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(GetResultItemModelFromJSON)),
    };
}

export function GetResponseModelToJSON(json: any): GetResponseModel {
    return GetResponseModelToJSONTyped(json, false);
}

export function GetResponseModelToJSONTyped(value?: GetResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(GetResultItemModelToJSON)),
    };
}

