/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for listing all indexes.
 * 
 * Attributes:
 *     indexes (List[str]): List of available index names.
 * @export
 * @interface IndexListResponseModel
 */
export interface IndexListResponseModel {
    /**
     * 
     * @type {Array<string>}
     * @memberof IndexListResponseModel
     */
    indexes: Array<string>;
}

/**
 * Check if a given object implements the IndexListResponseModel interface.
 */
export function instanceOfIndexListResponseModel(value: object): value is IndexListResponseModel {
    if (!('indexes' in value) || value['indexes'] === undefined) return false;
    return true;
}

export function IndexListResponseModelFromJSON(json: any): IndexListResponseModel {
    return IndexListResponseModelFromJSONTyped(json, false);
}

export function IndexListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'indexes': json['indexes'],
    };
}

export function IndexListResponseModelToJSON(json: any): IndexListResponseModel {
    return IndexListResponseModelToJSONTyped(json, false);
}

export function IndexListResponseModelToJSONTyped(value?: IndexListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'indexes': value['indexes'],
    };
}

