/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for performing operations on an existing index (e.g., delete, describe).
 * 
 * Attributes:
 *     index_key (str): A 32-byte encryption key as a hex string.
 *     index_name (str): The name/identifier of the index.
 * @export
 * @interface IndexOperationRequest
 */
export interface IndexOperationRequest {
    /**
     * 32-byte encryption key as hex string
     * @type {string}
     * @memberof IndexOperationRequest
     */
    indexKey: string;
    /**
     * ID name
     * @type {string}
     * @memberof IndexOperationRequest
     */
    indexName: string;
}

/**
 * Check if a given object implements the IndexOperationRequest interface.
 */
export function instanceOfIndexOperationRequest(value: object): value is IndexOperationRequest {
    if (!('indexKey' in value) || value['indexKey'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function IndexOperationRequestFromJSON(json: any): IndexOperationRequest {
    return IndexOperationRequestFromJSONTyped(json, false);
}

export function IndexOperationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexOperationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexKey': json['index_key'],
        'indexName': json['index_name'],
    };
}

export function IndexOperationRequestToJSON(json: any): IndexOperationRequest {
    return IndexOperationRequestToJSONTyped(json, false);
}

export function IndexOperationRequestToJSONTyped(value?: IndexOperationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
    };
}

