/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.16.3.dev86
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for retrieving the training status of indexes.
 * 
 * Attributes:
 *     training_indexes (List[str]): List of index names currently being trained or queued.
 *     retrain_threshold (int): The multiplier used for the retraining threshold.
 *     currently_training (Optional[str]): Name of the index currently being trained.
 *     queued_indexes (List[str]): List of indexes queued for training.
 *     worker_running (bool): Whether the training worker thread is running.
 *     worker_pid (int): Deprecated - kept for backward compatibility with SDK.
 *     global_training (Dict[str, Any]): Deprecated - kept for backward compatibility with SDK.
 * @export
 * @interface IndexTrainingStatusResponseModel
 */
export interface IndexTrainingStatusResponseModel {
    /**
     * 
     * @type {string}
     * @memberof IndexTrainingStatusResponseModel
     */
    currentlyTraining?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IndexTrainingStatusResponseModel
     */
    globalTraining?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof IndexTrainingStatusResponseModel
     */
    queuedIndexes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IndexTrainingStatusResponseModel
     */
    retrainThreshold: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof IndexTrainingStatusResponseModel
     */
    trainingIndexes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IndexTrainingStatusResponseModel
     */
    workerPid?: number;
    /**
     * 
     * @type {boolean}
     * @memberof IndexTrainingStatusResponseModel
     */
    workerRunning?: boolean;
}

/**
 * Check if a given object implements the IndexTrainingStatusResponseModel interface.
 */
export function instanceOfIndexTrainingStatusResponseModel(value: object): value is IndexTrainingStatusResponseModel {
    if (!('retrainThreshold' in value) || value['retrainThreshold'] === undefined) return false;
    if (!('trainingIndexes' in value) || value['trainingIndexes'] === undefined) return false;
    return true;
}

export function IndexTrainingStatusResponseModelFromJSON(json: any): IndexTrainingStatusResponseModel {
    return IndexTrainingStatusResponseModelFromJSONTyped(json, false);
}

export function IndexTrainingStatusResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexTrainingStatusResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'currentlyTraining': json['currently_training'] == null ? undefined : json['currently_training'],
        'globalTraining': json['global_training'] == null ? undefined : json['global_training'],
        'queuedIndexes': json['queued_indexes'] == null ? undefined : json['queued_indexes'],
        'retrainThreshold': json['retrain_threshold'],
        'trainingIndexes': json['training_indexes'],
        'workerPid': json['worker_pid'] == null ? undefined : json['worker_pid'],
        'workerRunning': json['worker_running'] == null ? undefined : json['worker_running'],
    };
}

export function IndexTrainingStatusResponseModelToJSON(json: any): IndexTrainingStatusResponseModel {
    return IndexTrainingStatusResponseModelToJSONTyped(json, false);
}

export function IndexTrainingStatusResponseModelToJSONTyped(value?: IndexTrainingStatusResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currently_training': value['currentlyTraining'],
        'global_training': value['globalTraining'],
        'queued_indexes': value['queuedIndexes'],
        'retrain_threshold': value['retrainThreshold'],
        'training_indexes': value['trainingIndexes'],
        'worker_pid': value['workerPid'],
        'worker_running': value['workerRunning'],
    };
}

