/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for retrieving the training status of indexes.
 * 
 * Attributes:
 *     training_indexes (List[str]): List of index names currently being trained.
 *     retrain_threshold (int): The multiplier used for the retraining threshold.
 * @export
 * @interface IndexTrainingStatusResponseModel
 */
export interface IndexTrainingStatusResponseModel {
    /**
     * 
     * @type {Array<string>}
     * @memberof IndexTrainingStatusResponseModel
     */
    trainingIndexes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IndexTrainingStatusResponseModel
     */
    retrainThreshold: number;
    /**
     * 
     * @type {number}
     * @memberof IndexTrainingStatusResponseModel
     */
    workerPid: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IndexTrainingStatusResponseModel
     */
    globalTraining: { [key: string]: any; };
}

/**
 * Check if a given object implements the IndexTrainingStatusResponseModel interface.
 */
export function instanceOfIndexTrainingStatusResponseModel(value: object): value is IndexTrainingStatusResponseModel {
    if (!('trainingIndexes' in value) || value['trainingIndexes'] === undefined) return false;
    if (!('retrainThreshold' in value) || value['retrainThreshold'] === undefined) return false;
    if (!('workerPid' in value) || value['workerPid'] === undefined) return false;
    if (!('globalTraining' in value) || value['globalTraining'] === undefined) return false;
    return true;
}

export function IndexTrainingStatusResponseModelFromJSON(json: any): IndexTrainingStatusResponseModel {
    return IndexTrainingStatusResponseModelFromJSONTyped(json, false);
}

export function IndexTrainingStatusResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexTrainingStatusResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'trainingIndexes': json['training_indexes'],
        'retrainThreshold': json['retrain_threshold'],
        'workerPid': json['worker_pid'],
        'globalTraining': json['global_training'],
    };
}

export function IndexTrainingStatusResponseModelToJSON(json: any): IndexTrainingStatusResponseModel {
    return IndexTrainingStatusResponseModelToJSONTyped(json, false);
}

export function IndexTrainingStatusResponseModelToJSONTyped(value?: IndexTrainingStatusResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'training_indexes': value['trainingIndexes'],
        'retrain_threshold': value['retrainThreshold'],
        'worker_pid': value['workerPid'],
        'global_training': value['globalTraining'],
    };
}

