/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BM25Config } from './BM25Config';
import {
    BM25ConfigFromJSON,
    BM25ConfigToJSON,
} from './BM25Config';
import type { MetadataFieldPolicy } from './MetadataFieldPolicy';
import {
    MetadataFieldPolicyFromJSON,
    MetadataFieldPolicyToJSON,
} from './MetadataFieldPolicy';

/**
 * Response model for retrieving information about an index.
 * 
 * Attributes:
 *     index_name (str): The name of the index.
 *     is_trained (bool): Indicates whether the index has been trained.
 *     dimension (int): Dimensionality of the vectors. `0` before the
 *         first upsert when create_index was called without an explicit
 *         dimension (auto-detect).
 *     metric (str): Distance metric (`euclidean`, `cosine`, or
 *         `squared_euclidean`).
 *     n_lists (int): Number of inverted lists in the IVF index. `1`
 *         for untrained indexes.
 *     metadata_schema (Dict[str, MetadataFieldPolicy]): Per-field metadata
 *         indexing overrides recorded at create time. Empty when the
 *         index uses the default index-everything posture.
 *     bm25 (Optional[BM25Config]): BM25 scoring config when the index has
 *         at least one full_text field; `None` otherwise.
 * @export
 * @interface IndexInfoResponseModel
 */
export interface IndexInfoResponseModel {
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponseModel
     */
    indexName: string;
    /**
     * 
     * @type {boolean}
     * @memberof IndexInfoResponseModel
     */
    isTrained: boolean;
    /**
     * 
     * @type {number}
     * @memberof IndexInfoResponseModel
     */
    dimension: number;
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponseModel
     */
    metric: string;
    /**
     * 
     * @type {number}
     * @memberof IndexInfoResponseModel
     */
    nLists: number;
    /**
     * 
     * @type {{ [key: string]: MetadataFieldPolicy; }}
     * @memberof IndexInfoResponseModel
     */
    metadataSchema?: { [key: string]: MetadataFieldPolicy; };
    /**
     * 
     * @type {BM25Config}
     * @memberof IndexInfoResponseModel
     */
    bm25?: BM25Config | null;
}

/**
 * Check if a given object implements the IndexInfoResponseModel interface.
 */
export function instanceOfIndexInfoResponseModel(value: object): value is IndexInfoResponseModel {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('isTrained' in value) || value['isTrained'] === undefined) return false;
    if (!('dimension' in value) || value['dimension'] === undefined) return false;
    if (!('metric' in value) || value['metric'] === undefined) return false;
    if (!('nLists' in value) || value['nLists'] === undefined) return false;
    return true;
}

export function IndexInfoResponseModelFromJSON(json: any): IndexInfoResponseModel {
    return IndexInfoResponseModelFromJSONTyped(json, false);
}

export function IndexInfoResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexInfoResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'indexName': json['index_name'],
        'isTrained': json['is_trained'],
        'dimension': json['dimension'],
        'metric': json['metric'],
        'nLists': json['n_lists'],
        'metadataSchema': json['metadata_schema'] == null ? undefined : (mapValues(json['metadata_schema'], MetadataFieldPolicyFromJSON)),
        'bm25': json['bm25'] == null ? undefined : BM25ConfigFromJSON(json['bm25']),
    };
}

export function IndexInfoResponseModelToJSON(json: any): IndexInfoResponseModel {
    return IndexInfoResponseModelToJSONTyped(json, false);
}

export function IndexInfoResponseModelToJSONTyped(value?: IndexInfoResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_name': value['indexName'],
        'is_trained': value['isTrained'],
        'dimension': value['dimension'],
        'metric': value['metric'],
        'n_lists': value['nLists'],
        'metadata_schema': value['metadataSchema'] == null ? undefined : (mapValues(value['metadataSchema'], MetadataFieldPolicyToJSON)),
        'bm25': BM25ConfigToJSON(value['bm25']),
    };
}

