/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for retrieving information about an index.
 * 
 * Attributes:
 *     index_name (str): The name of the index.
 *     index_type (str): The type of index (e.g., IVF, IVFFlat, IVFPQ).
 *     is_trained (bool): Indicates whether the index has been trained.
 *     index_config (Dict[str, Any]): The full configuration details of the index.
 * @export
 * @interface IndexInfoResponseModel
 */
export interface IndexInfoResponseModel {
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponseModel
     */
    indexName: string;
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponseModel
     */
    indexType: string;
    /**
     * 
     * @type {boolean}
     * @memberof IndexInfoResponseModel
     */
    isTrained: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IndexInfoResponseModel
     */
    indexConfig: { [key: string]: any; };
}

/**
 * Check if a given object implements the IndexInfoResponseModel interface.
 */
export function instanceOfIndexInfoResponseModel(value: object): value is IndexInfoResponseModel {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('indexType' in value) || value['indexType'] === undefined) return false;
    if (!('isTrained' in value) || value['isTrained'] === undefined) return false;
    if (!('indexConfig' in value) || value['indexConfig'] === undefined) return false;
    return true;
}

export function IndexInfoResponseModelFromJSON(json: any): IndexInfoResponseModel {
    return IndexInfoResponseModelFromJSONTyped(json, false);
}

export function IndexInfoResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexInfoResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'indexName': json['index_name'],
        'indexType': json['index_type'],
        'isTrained': json['is_trained'],
        'indexConfig': json['index_config'],
    };
}

export function IndexInfoResponseModelToJSON(json: any): IndexInfoResponseModel {
    return IndexInfoResponseModelToJSONTyped(json, false);
}

export function IndexInfoResponseModelToJSONTyped(value?: IndexInfoResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_name': value['indexName'],
        'index_type': value['indexType'],
        'is_trained': value['isTrained'],
        'index_config': value['indexConfig'],
    };
}

