/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for configuring an IVFSQ (Inverted File with Scalar Quantization) index.
 * 
 * Attributes:
 *     type (str): Index type identifier. Defaults to "ivfsq".
 *     sq_bits (int): Number of bits per dimension for scalar quantization. Defaults to 16.
 * @export
 * @interface IndexIVFSQModel
 */
export interface IndexIVFSQModel {
    /**
     * 
     * @type {number}
     * @memberof IndexIVFSQModel
     */
    dimension?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IndexIVFSQModel
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof IndexIVFSQModel
     */
    sqBits?: number;
}

/**
 * Check if a given object implements the IndexIVFSQModel interface.
 */
export function instanceOfIndexIVFSQModel(value: object): value is IndexIVFSQModel {
    return true;
}

export function IndexIVFSQModelFromJSON(json: any): IndexIVFSQModel {
    return IndexIVFSQModelFromJSONTyped(json, false);
}

export function IndexIVFSQModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexIVFSQModel {
    if (json == null) {
        return json;
    }
    return {
        
        'dimension': json['dimension'] == null ? undefined : json['dimension'],
        'type': json['type'] == null ? undefined : json['type'],
        'sqBits': json['sq_bits'] == null ? undefined : json['sq_bits'],
    };
}

export function IndexIVFSQModelToJSON(json: any): IndexIVFSQModel {
    return IndexIVFSQModelToJSONTyped(json, false);
}

export function IndexIVFSQModelToJSONTyped(value?: IndexIVFSQModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dimension': value['dimension'],
        'type': value['type'],
        'sq_bits': value['sqBits'],
    };
}

