/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.16.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for performing operations on an existing index (e.g., delete, describe).
 * 
 * Exactly one of two paths applies on every request:
 *   * `index_key` is supplied — used as the KEK for the index.  The
 *     index's `KMSBlob` may be `provider: none` (SDK-supplied path)
 *     or a real KMS slot (the SDK-supplied key is then validated
 *     against the cached hash).
 *   * `index_key` is omitted — the index must be KMS-backed.  The
 *     service reads the `KMSBlob` snapshot, resolves the KEK via
 *     the named KMS (cached by the `kek_cache` TTL), and uses that.
 * 
 * Attributes:
 *     index_name (str): The name/identifier of the index.
 *     index_key (str, optional): 32-byte encryption key as hex string.
 *         Required for `provider: none` indexes (the SDK owns the
 *         KEK); optional for KMS-backed indexes.
 * @export
 * @interface IndexOperationRequest
 */
export interface IndexOperationRequest {
    /**
     * ID name
     * @type {string}
     * @memberof IndexOperationRequest
     */
    indexName: string;
    /**
     * 
     * @type {string}
     * @memberof IndexOperationRequest
     */
    indexKey?: string | null;
}

/**
 * Check if a given object implements the IndexOperationRequest interface.
 */
export function instanceOfIndexOperationRequest(value: object): value is IndexOperationRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function IndexOperationRequestFromJSON(json: any): IndexOperationRequest {
    return IndexOperationRequestFromJSONTyped(json, false);
}

export function IndexOperationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexOperationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexName': json['index_name'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
    };
}

export function IndexOperationRequestToJSON(json: any): IndexOperationRequest {
    return IndexOperationRequestToJSONTyped(json, false);
}

export function IndexOperationRequestToJSONTyped(value?: IndexOperationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_name': value['indexName'],
        'index_key': value['indexKey'],
    };
}

