/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for listing all IDs in the index.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * @export
 * @interface ListIDsRequest
 */
export interface ListIDsRequest {
    /**
     * 32-byte encryption key as hex string
     * @type {string}
     * @memberof ListIDsRequest
     */
    indexKey: string;
    /**
     * ID name
     * @type {string}
     * @memberof ListIDsRequest
     */
    indexName: string;
}

/**
 * Check if a given object implements the ListIDsRequest interface.
 */
export function instanceOfListIDsRequest(value: object): value is ListIDsRequest {
    if (!('indexKey' in value) || value['indexKey'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function ListIDsRequestFromJSON(json: any): ListIDsRequest {
    return ListIDsRequestFromJSONTyped(json, false);
}

export function ListIDsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIDsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexKey': json['index_key'],
        'indexName': json['index_name'],
    };
}

export function ListIDsRequestToJSON(json: any): ListIDsRequest {
    return ListIDsRequestToJSONTyped(json, false);
}

export function ListIDsRequestToJSONTyped(value?: ListIDsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
    };
}

