/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for listing all IDs in the index.
 * 
 * Attributes:
 *     ids (List[str]): List of all item IDs in the index.
 *     count (int): Total number of IDs in the index.
 * @export
 * @interface ListIDsResponse
 */
export interface ListIDsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListIDsResponse
     */
    ids: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ListIDsResponse
     */
    count: number;
}

/**
 * Check if a given object implements the ListIDsResponse interface.
 */
export function instanceOfListIDsResponse(value: object): value is ListIDsResponse {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ListIDsResponseFromJSON(json: any): ListIDsResponse {
    return ListIDsResponseFromJSONTyped(json, false);
}

export function ListIDsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIDsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'count': json['count'],
    };
}

export function ListIDsResponseToJSON(json: any): ListIDsResponse {
    return ListIDsResponseToJSONTyped(json, false);
}

export function ListIDsResponseToJSONTyped(value?: ListIDsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
        'count': value['count'],
    };
}

