/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Per-field metadata indexing policy (one entry of `metadata_schema`).
 * 
 * Metadata itself stays schemaless — this is indexing policy, not
 * validation.  Fields omitted from `metadata_schema` inherit the
 * index-everything default.
 * 
 * Attributes:
 *     filterable: Build inverted-index postings for the field, so
 *         filters on it resolve from the index (pre-filter).  When
 *         `false`, the field is still stored and still filterable, but
 *         a filter referencing it forces the dense forward-blob
 *         post-filter path — cheaper writes, slower filtered queries.
 *     pattern: Additionally build the field's regex dictionary, which
 *         makes `$regex` / `$contains` resolvable from the index.
 *         Requires `filterable=true`.
 *     full_text: Route the field's string value through the BM25
 *         analyzer instead of exact-match indexing.  This is what makes
 *         the field searchable by `query_metadata(text=...)` and hybrid
 *         `query(text=...)`.  A field is either analyzed or exact-match
 *         indexed, so `full_text=true` is incompatible with both
 *         `pattern=true` and an explicit `filterable=true`, and implies
 *         `filterable=false`.
 * @export
 * @interface MetadataFieldPolicy
 */
export interface MetadataFieldPolicy {
    /**
     * 
     * @type {boolean}
     * @memberof MetadataFieldPolicy
     */
    filterable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataFieldPolicy
     */
    pattern?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataFieldPolicy
     */
    fullText?: boolean;
}

/**
 * Check if a given object implements the MetadataFieldPolicy interface.
 */
export function instanceOfMetadataFieldPolicy(value: object): value is MetadataFieldPolicy {
    return true;
}

export function MetadataFieldPolicyFromJSON(json: any): MetadataFieldPolicy {
    return MetadataFieldPolicyFromJSONTyped(json, false);
}

export function MetadataFieldPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataFieldPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'filterable': json['filterable'] == null ? undefined : json['filterable'],
        'pattern': json['pattern'] == null ? undefined : json['pattern'],
        'fullText': json['full_text'] == null ? undefined : json['full_text'],
    };
}

export function MetadataFieldPolicyToJSON(json: any): MetadataFieldPolicy {
    return MetadataFieldPolicyToJSONTyped(json, false);
}

export function MetadataFieldPolicyToJSONTyped(value?: MetadataFieldPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filterable': value['filterable'],
        'pattern': value['pattern'],
        'full_text': value['fullText'],
    };
}

