/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * One row of a ``query_metadata`` result: the item id, plus a BM25 score when there is one.
 * 
 * ``score`` is present only on the text path. A filter-only query has nothing to score, so the
 * key is absent rather than ``None`` — the same rule ``query()`` follows for ``distance`` and
 * ``score``. Callers do not branch in practice: whoever passed ``text`` knows the key is there.
 * 
 * Split across two TypedDicts because that is how a per-key optional is expressed before
 * ``typing.NotRequired`` (3.11); the package supports 3.10, and inheriting with ``total=False``
 * keeps ``id`` required while making ``score`` optional — one result type, no union, no
 * ``typing_extensions`` dependency.
 * 
 * Note the package ships no ``py.typed`` marker, so this reaches editors reading the source but
 * not a consumer's mypy/pyright — see the plan's v2 note.
 * @export
 * @interface MetadataResult
 */
export interface MetadataResult {
    /**
     * 
     * @type {string}
     * @memberof MetadataResult
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof MetadataResult
     */
    score?: number;
}

/**
 * Check if a given object implements the MetadataResult interface.
 */
export function instanceOfMetadataResult(value: object): value is MetadataResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MetadataResultFromJSON(json: any): MetadataResult {
    return MetadataResultFromJSONTyped(json, false);
}

export function MetadataResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function MetadataResultToJSON(json: any): MetadataResult {
    return MetadataResultToJSONTyped(json, false);
}

export function MetadataResultToJSONTyped(value?: MetadataResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'score': value['score'],
    };
}

