/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Metadata field to sort matches by, applied after filtering. Accepts a field name, or a single-field MongoDB-style dict such as {'views': -1} (1 ascending, -1 descending) which overrides `ascending`. Unordered when omitted. Items missing the field, or holding a non-scalar, sort last. Not supported with `text`.
 * @export
 * @interface OrderBy
 */
export interface OrderBy {
}

/**
 * Check if a given object implements the OrderBy interface.
 */
export function instanceOfOrderBy(value: object): value is OrderBy {
    return true;
}

export function OrderByFromJSON(json: any): OrderBy {
    return OrderByFromJSONTyped(json, false);
}

export function OrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBy {
    return json;
}

export function OrderByToJSON(json: any): OrderBy {
    return OrderByToJSONTyped(json, false);
}

export function OrderByToJSONTyped(value?: OrderBy | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

