/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request model for a metadata-only query (no query vector).
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like
 *         dictionary. Unlike `/query`, every leaf must be resolvable from
 *         the metadata index — see the field description.
 *     top_k (Optional[int]): Cap on the number of ids returned. `None`
 *         returns every match. Applied AFTER `order_by`.
 *     order_by (Optional[str]): Metadata field to sort the matches by
 *         (post-filter). Unordered when omitted.
 *     ascending (bool): Sort direction when `order_by` is set.
 * @export
 * @interface QueryMetadataRequest
 */
export interface QueryMetadataRequest {
    /**
     * ID name
     * @type {string}
     * @memberof QueryMetadataRequest
     */
    indexName: string;
    /**
     * 32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).
     * @type {string}
     * @memberof QueryMetadataRequest
     */
    indexKey?: string | null;
    /**
     * Arbitrary JSON object stored alongside the vector. Schemaless — the index's `metadata_schema` governs how fields are indexed, not what may be stored. Nested objects are addressable by dot-path in filters (`loc.city`); dates have no native type, store them as epoch millis.
     * @type {{ [key: string]: any; }}
     * @memberof QueryMetadataRequest
     */
    filters?: { [key: string]: any; } | null;
    /**
     * Cap on the number of ids returned; omit for all matches. Applied after `order_by`, so it yields the first N of the sorted result.
     * @type {number}
     * @memberof QueryMetadataRequest
     */
    topK?: number | null;
    /**
     * Metadata field to sort matches by, applied after filtering. Unordered when omitted. Items missing the field, or holding a non-scalar, sort last.
     * @type {string}
     * @memberof QueryMetadataRequest
     */
    orderBy?: string | null;
    /**
     * Sort direction when `order_by` is set.
     * @type {boolean}
     * @memberof QueryMetadataRequest
     */
    ascending?: boolean;
}

/**
 * Check if a given object implements the QueryMetadataRequest interface.
 */
export function instanceOfQueryMetadataRequest(value: object): value is QueryMetadataRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function QueryMetadataRequestFromJSON(json: any): QueryMetadataRequest {
    return QueryMetadataRequestFromJSONTyped(json, false);
}

export function QueryMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexName': json['index_name'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'orderBy': json['order_by'] == null ? undefined : json['order_by'],
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
    };
}

export function QueryMetadataRequestToJSON(json: any): QueryMetadataRequest {
    return QueryMetadataRequestToJSONTyped(json, false);
}

export function QueryMetadataRequestToJSONTyped(value?: QueryMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_name': value['indexName'],
        'index_key': value['indexKey'],
        'filters': value['filters'],
        'top_k': value['topK'],
        'order_by': value['orderBy'],
        'ascending': value['ascending'],
    };
}

