/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request model for performing a similarity search in the encrypted index.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     query_vectors (Optional[List[float]]): The vector used for the similarity search.
 *     query_contents (Optional[str]): Text-based content used for semantic search.
 *     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.
 *     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.
 *     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.
 *     rerank_mult (Optional[int]): Multiplier for stage 1 retrieval in reranking indexes. Defaults to 10.
 *     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like
 *         dictionary (see `FILTERS_DESCRIPTION` for the operator set).
 *         Defaults to {}.
 *     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * ID name
     * @type {string}
     * @memberof QueryRequest
     */
    indexName: string;
    /**
     * 32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).
     * @type {string}
     * @memberof QueryRequest
     */
    indexKey?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof QueryRequest
     */
    queryVectors?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    queryContents?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    topK?: number | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    nProbes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    rerankMult?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof QueryRequest
     */
    greedy?: boolean | null;
    /**
     * Metadata filters as a JSON object. Operators: `$eq`, `$ne`, `$in`, `$nin`, `$exists`, `$gt`, `$gte`, `$lt`, `$lte`, `$regex`, `$contains`, combined with `$and` / `$or` / `$nor` / `$not`. Filtering works on any metadata field; the index's `metadata_schema` only decides how a filter is resolved — fields marked `filterable` (the default) are answered from the inverted index, and `$regex` / `$contains` are answered from the regex dictionary on `pattern` fields. Anything else falls back to a post-filter over the decrypted metadata, which is correct but slower. Dates have no native type: store and filter them as epoch milliseconds.
     * @type {{ [key: string]: any; }}
     * @memberof QueryRequest
     */
    filters?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryRequest
     */
    include?: Array<string>;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): value is QueryRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexName': json['index_name'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'queryVectors': json['query_vectors'] == null ? undefined : json['query_vectors'],
        'queryContents': json['query_contents'] == null ? undefined : json['query_contents'],
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'nProbes': json['n_probes'] == null ? undefined : json['n_probes'],
        'rerankMult': json['rerank_mult'] == null ? undefined : json['rerank_mult'],
        'greedy': json['greedy'] == null ? undefined : json['greedy'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'include': json['include'] == null ? undefined : json['include'],
    };
}

export function QueryRequestToJSON(json: any): QueryRequest {
    return QueryRequestToJSONTyped(json, false);
}

export function QueryRequestToJSONTyped(value?: QueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_name': value['indexName'],
        'index_key': value['indexKey'],
        'query_vectors': value['queryVectors'],
        'query_contents': value['queryContents'],
        'top_k': value['topK'],
        'n_probes': value['nProbes'],
        'rerank_mult': value['rerankMult'],
        'greedy': value['greedy'],
        'filters': value['filters'],
        'include': value['include'],
    };
}

