/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.1.dev16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MetadataResult } from './MetadataResult';
import {
    MetadataResultFromJSON,
    MetadataResultToJSON,
} from './MetadataResult';

/**
 * Response model for a metadata query.
 * 
 * Attributes:
 *     results (List[MetadataResult]): Matching items, using core's row shape
 *         directly. On a `text=...` query each row is `{id, score}` in
 *         descending score order; on a filter-only query each row is `{id}`
 *         (no `score` key — there is nothing to score) following `order_by`
 *         when set, else an unordered subset.
 *     ids (List[str]): Matching item IDs, parallel to `results`. Retained
 *         for backward compatibility with callers that only read IDs.
 *     count (int): Number of items returned.
 * @export
 * @interface QueryMetadataResponse
 */
export interface QueryMetadataResponse {
    /**
     * 
     * @type {Array<MetadataResult>}
     * @memberof QueryMetadataResponse
     */
    results?: Array<MetadataResult>;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryMetadataResponse
     */
    ids: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof QueryMetadataResponse
     */
    count: number;
}

/**
 * Check if a given object implements the QueryMetadataResponse interface.
 */
export function instanceOfQueryMetadataResponse(value: object): value is QueryMetadataResponse {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function QueryMetadataResponseFromJSON(json: any): QueryMetadataResponse {
    return QueryMetadataResponseFromJSONTyped(json, false);
}

export function QueryMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(MetadataResultFromJSON)),
        'ids': json['ids'],
        'count': json['count'],
    };
}

export function QueryMetadataResponseToJSON(json: any): QueryMetadataResponse {
    return QueryMetadataResponseToJSONTyped(json, false);
}

export function QueryMetadataResponseToJSONTyped(value?: QueryMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(MetadataResultToJSON)),
        'ids': value['ids'],
        'count': value['count'],
    };
}

