/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request model for training an index.
 * 
 * Attributes:
 *     n_lists (Optional[int]): Number of lists/clusters for the index. Default is auto.
 *     batch_size (Optional[int]): Size of each batch for training. Default is 2048.
 *     max_iters (Optional[int]): Maximum iterations for training. Default is 100.
 *     tolerance (Optional[float]): Convergence tolerance for training. Default is 1e-6.
 *     max_memory (Optional[int]): Maximum memory (MB) usage during training. Default is 0 (no limit).
 * @export
 * @interface TrainRequest
 */
export interface TrainRequest {
    /**
     * 
     * @type {number}
     * @memberof TrainRequest
     */
    batchSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrainRequest
     */
    indexKey?: string | null;
    /**
     * ID name
     * @type {string}
     * @memberof TrainRequest
     */
    indexName: string;
    /**
     * 
     * @type {number}
     * @memberof TrainRequest
     */
    maxIters?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrainRequest
     */
    maxMemory?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrainRequest
     */
    nLists?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrainRequest
     */
    tolerance?: number | null;
}

/**
 * Check if a given object implements the TrainRequest interface.
 */
export function instanceOfTrainRequest(value: object): value is TrainRequest {
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function TrainRequestFromJSON(json: any): TrainRequest {
    return TrainRequestFromJSONTyped(json, false);
}

export function TrainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'indexKey': json['index_key'] == null ? undefined : json['index_key'],
        'indexName': json['index_name'],
        'maxIters': json['max_iters'] == null ? undefined : json['max_iters'],
        'maxMemory': json['max_memory'] == null ? undefined : json['max_memory'],
        'nLists': json['n_lists'] == null ? undefined : json['n_lists'],
        'tolerance': json['tolerance'] == null ? undefined : json['tolerance'],
    };
}

export function TrainRequestToJSON(json: any): TrainRequest {
    return TrainRequestToJSONTyped(json, false);
}

export function TrainRequestToJSONTyped(value?: TrainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batch_size': value['batchSize'],
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
        'max_iters': value['maxIters'],
        'max_memory': value['maxMemory'],
        'n_lists': value['nLists'],
        'tolerance': value['tolerance'],
    };
}

