/* tslint:disable */
/* eslint-disable */
/**
 * CyborgDB Service
 * REST API for CyborgDB: The Confidential Vector Database
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VectorItem } from './VectorItem';
import {
    VectorItemFromJSON,
    VectorItemFromJSONTyped,
    VectorItemToJSON,
    VectorItemToJSONTyped,
} from './VectorItem';

/**
 * Request model for adding or updating vectors in an encrypted index.
 * 
 * Inherits:
 *     IndexOperationRequest: Includes `index_name` and `index_key`.
 * 
 * Attributes:
 *     items (List[VectorItem]): List of vector items to be inserted or updated.
 * @export
 * @interface UpsertRequest
 */
export interface UpsertRequest {
    /**
     * 32-byte encryption key as hex string
     * @type {string}
     * @memberof UpsertRequest
     */
    indexKey: string;
    /**
     * ID name
     * @type {string}
     * @memberof UpsertRequest
     */
    indexName: string;
    /**
     * 
     * @type {Array<VectorItem>}
     * @memberof UpsertRequest
     */
    items: Array<VectorItem>;
}

/**
 * Check if a given object implements the UpsertRequest interface.
 */
export function instanceOfUpsertRequest(value: object): value is UpsertRequest {
    if (!('indexKey' in value) || value['indexKey'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function UpsertRequestFromJSON(json: any): UpsertRequest {
    return UpsertRequestFromJSONTyped(json, false);
}

export function UpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'indexKey': json['index_key'],
        'indexName': json['index_name'],
        'items': ((json['items'] as Array<any>).map(VectorItemFromJSON)),
    };
}

export function UpsertRequestToJSON(json: any): UpsertRequest {
    return UpsertRequestToJSONTyped(json, false);
}

export function UpsertRequestToJSONTyped(value?: UpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_key': value['indexKey'],
        'index_name': value['indexName'],
        'items': ((value['items'] as Array<any>).map(VectorItemToJSON)),
    };
}

